import type { MockPlace } from "@/components/plan-wizard/PlaceSwiper";

export const MOCK_MODE = true; // TODO: zmień na false przed launche'm

// Free deterministic photos — no API key, no billing
const pic = (seed: string) => `https://picsum.photos/seed/${seed}/800/600`;

export const MOCK_PLACES: MockPlace[] = [
  // ── Kraków ──────────────────────────────────────────────────────────────────
  {
    id: "mock-krakow-1",
    place_name: "Wawel",
    category: "monument",
    city: "Kraków",
    address: "Wawel 5, 31-001 Kraków",
    latitude: 50.0543,
    longitude: 19.9352,
    rating: 4.8,
    photo_url: pic("wawel-castle"),
    vibe_tags: ["historia", "widok", "must-see"],
    description: "Królewski zamek na wzgórzu z katedrą, smoczą jaskinią i skarbcem koronnym.",
  },
  {
    id: "mock-krakow-2",
    place_name: "Sukiennice",
    category: "market",
    city: "Kraków",
    address: "Rynek Główny 1, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9373,
    rating: 4.6,
    photo_url: pic("krakow-market"),
    vibe_tags: ["zakupy", "centrum", "pamiątki"],
    description: "Renesansowa hala targowa w sercu Rynku Głównego, pełna kramów z polskim rękodzielnictwem.",
  },
  {
    id: "mock-krakow-3",
    place_name: "Kawiarnia Płyś",
    category: "cafe",
    city: "Kraków",
    address: "ul. Floriańska 12, 31-021 Kraków",
    latitude: 50.0610,
    longitude: 19.9360,
    rating: 4.5,
    photo_url: pic("cozy-cafe-interior"),
    vibe_tags: ["kawa", "klimat", "slow"],
    description: "Kultowa krakowska kawiarnia ze świetną kawą i domowymi ciastkami.",
  },
  {
    id: "mock-krakow-4",
    place_name: "MOCAK",
    category: "museum",
    city: "Kraków",
    address: "ul. Lipowa 4, 30-702 Kraków",
    latitude: 50.0519,
    longitude: 19.9601,
    rating: 4.4,
    photo_url: pic("modern-art-museum"),
    vibe_tags: ["sztuka", "kultura", "współczesność"],
    description: "Muzeum Sztuki Współczesnej w Krakowie — prowokujące wystawy w dawnej fabryce Schindlera.",
  },
  {
    id: "mock-krakow-5",
    place_name: "Kazimierz",
    category: "experience",
    city: "Kraków",
    address: "Kazimierz, 31-056 Kraków",
    latitude: 50.0517,
    longitude: 19.9431,
    rating: 4.7,
    photo_url: pic("kazimierz-krakow"),
    vibe_tags: ["klimat", "bary", "historia"],
    description: "Historyczna żydowska dzielnica pełna galerii, barów i klimatycznych podwórek.",
  },
  {
    id: "mock-krakow-6",
    place_name: "Planty",
    category: "park",
    city: "Kraków",
    address: "Park Planty, Kraków",
    latitude: 50.0597,
    longitude: 19.9375,
    rating: 4.6,
    photo_url: pic("city-park-green"),
    vibe_tags: ["spacer", "relaks", "natura"],
    description: "Pierścień zieleni okalający Stare Miasto — idealne miejsce na poranny spacer.",
  },
  {
    id: "mock-krakow-7",
    place_name: "Kościół Mariacki",
    category: "monument",
    city: "Kraków",
    address: "pl. Mariacki 5, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9390,
    rating: 4.8,
    photo_url: pic("gothic-church-tower"),
    vibe_tags: ["architektura", "historia", "ołtarz Wita Stwosza"],
    description: "Gotycka bazylika z XIV w. z hejnałem i słynnym ołtarzem Wita Stwosza.",
  },
  {
    id: "mock-krakow-8",
    place_name: "Veganico",
    category: "restaurant",
    city: "Kraków",
    address: "ul. Sławkowska 8, 31-014 Kraków",
    latitude: 50.0618,
    longitude: 19.9350,
    rating: 4.5,
    photo_url: pic("vegan-restaurant-food"),
    vibe_tags: ["vege", "zdrowe", "lunch"],
    description: "Wegańska restauracja w centrum — kolorowe miski i smoothie, idealne na lunch.",
  },
  {
    id: "mock-krakow-9",
    place_name: "Hala Targowa Stary Kleparz",
    category: "market",
    city: "Kraków",
    address: "ul. Krowoderska 22, 31-141 Kraków",
    latitude: 50.0672,
    longitude: 19.9390,
    rating: 4.3,
    photo_url: pic("local-food-market"),
    vibe_tags: ["lokalnie", "śniadanie", "warzywa"],
    description: "Jeden z najstarszych targów w Krakowie — świeże produkty od lokalnych rolników.",
  },
  {
    id: "mock-krakow-10",
    place_name: "Bar Mleczny Centralny",
    category: "restaurant",
    city: "Kraków",
    address: "ul. Jagiellońska 1, 31-010 Kraków",
    latitude: 50.0628,
    longitude: 19.9362,
    rating: 4.2,
    photo_url: pic("polish-milk-bar"),
    vibe_tags: ["tanie jedzenie", "nostalgiczny", "klasyk"],
    description: "Kultowy bar mleczny z czasów PRL — pierogi, żurek i kompot w niebiciu cenach.",
  },
  {
    id: "mock-krakow-11",
    place_name: "Muzeum Narodowe",
    category: "museum",
    city: "Kraków",
    address: "al. 3 Maja 1, 30-062 Kraków",
    latitude: 50.0587,
    longitude: 19.9262,
    rating: 4.5,
    photo_url: pic("national-museum-art"),
    vibe_tags: ["sztuka", "kultura", "malarstwo"],
    description: "Największe muzeum w Polsce z bogatą kolekcją polskiego malarstwa i rzemiosła.",
  },
  {
    id: "mock-krakow-12",
    place_name: "Forum Przestrzenie",
    category: "bar",
    city: "Kraków",
    address: "ul. Marii Konopnickiej 28, 30-302 Kraków",
    latitude: 50.0521,
    longitude: 19.9358,
    rating: 4.4,
    photo_url: pic("riverside-bar-terrace"),
    vibe_tags: ["taras", "Wisła", "koktajle"],
    description: "Bar na tarasie dawnego hotelu Forum z zapierającym widokiem na Wisłę i Wawel.",
  },
  // ── Warszawa ─────────────────────────────────────────────────────────────────
  {
    id: "mock-warszawa-1",
    place_name: "Stare Miasto",
    category: "monument",
    city: "Warszawa",
    address: "Stare Miasto, 00-272 Warszawa",
    latitude: 52.2497,
    longitude: 21.0122,
    rating: 4.6,
    photo_url: pic("warsaw-old-town"),
    vibe_tags: ["historia", "spacer", "odbudowane"],
    description: "Pięknie odbudowane Stare Miasto wpisane na listę UNESCO.",
  },
  {
    id: "mock-warszawa-2",
    place_name: "Centrum Nauki Kopernik",
    category: "experience",
    city: "Warszawa",
    address: "Wybrzeże Kościuszkowskie 20, 00-390 Warszawa",
    latitude: 52.2415,
    longitude: 21.0281,
    rating: 4.7,
    photo_url: pic("science-center-exhibit"),
    vibe_tags: ["nauka", "interaktywnie", "dla wszystkich"],
    description: "Interaktywne muzeum nauki z setkami eksponatów do samodzielnego odkrywania.",
  },
  {
    id: "mock-warszawa-3",
    place_name: "Hala Koszyki",
    category: "restaurant",
    city: "Warszawa",
    address: "ul. Koszykowa 63, 02-008 Warszawa",
    latitude: 52.2227,
    longitude: 21.0157,
    rating: 4.5,
    photo_url: pic("food-hall-indoor"),
    vibe_tags: ["food hall", "różnorodność", "lunch"],
    description: "Zabytkowa hala targowa zamieniona w modne miejsce z kuchnią z całego świata.",
  },
  // ── Gdańsk ───────────────────────────────────────────────────────────────────
  {
    id: "mock-gdansk-1",
    place_name: "Długi Targ",
    category: "viewpoint",
    city: "Gdańsk",
    address: "Długi Targ, 80-827 Gdańsk",
    latitude: 54.3490,
    longitude: 18.6531,
    rating: 4.7,
    photo_url: pic("gdansk-harbor-street"),
    vibe_tags: ["widok", "kamienice", "centrum"],
    description: "Reprezentacyjna ulica Gdańska z Fontanną Neptuna i Dworem Artusa.",
  },
  {
    id: "mock-gdansk-2",
    place_name: "Muzeum II Wojny Światowej",
    category: "museum",
    city: "Gdańsk",
    address: "pl. Władysława Bartoszewskiego 1, 80-862 Gdańsk",
    latitude: 54.3565,
    longitude: 18.6508,
    rating: 4.8,
    photo_url: pic("war-museum-exhibition"),
    vibe_tags: ["historia", "poruszające", "must-see"],
    description: "Jedno z najważniejszych muzeów historycznych w Europie — poruszająca narracja o wojnie.",
  },
  // ── Wrocław ──────────────────────────────────────────────────────────────────
  {
    id: "mock-wroclaw-1",
    place_name: "Ostrów Tumski",
    category: "monument",
    city: "Wrocław",
    address: "Ostrów Tumski, 50-329 Wrocław",
    latitude: 51.1147,
    longitude: 17.0463,
    rating: 4.7,
    photo_url: pic("cathedral-island-river"),
    vibe_tags: ["katedra", "most", "wieczór"],
    description: "Historyczna wyspa z katedrą — magiczne miejsce szczególnie po zmierzchu.",
  },
  {
    id: "mock-wroclaw-2",
    place_name: "Hala Stulecia",
    category: "experience",
    city: "Wrocław",
    address: "ul. Wystawowa 1, 51-618 Wrocław",
    latitude: 51.1071,
    longitude: 17.0774,
    rating: 4.5,
    photo_url: pic("historic-dome-building"),
    vibe_tags: ["architektura", "UNESCO", "events"],
    description: "Modernistyczna hala z 1913 r. wpisana na listę UNESCO — ikona wrocławskiej architektury.",
  },

  // ── Łódź ─────────────────────────────────────────────────────────────────────
  {
    id: "mock-lodz-1",
    place_name: "Manufaktura",
    category: "experience",
    city: "Łódź",
    address: "ul. Drewnowska 58, 91-002 Łódź",
    latitude: 51.7773,
    longitude: 19.4472,
    rating: 4.7,
    photo_url: pic("manufaktura-lodz-factory"),
    vibe_tags: ["must-see", "kultura", "zakupy"],
    description: "Największe centrum kultury, rozrywki i handlu w Polsce — w dawnej fabryce Izraela Poznańskiego.",
  },
  {
    id: "mock-lodz-2",
    place_name: "Piotrkowska",
    category: "experience",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7558,
    longitude: 19.4553,
    rating: 4.6,
    photo_url: pic("lodz-piotrkowska-street"),
    vibe_tags: ["spacer", "kawiarnie", "centrum"],
    description: "Jedna z najdłuższych ulic handlowych w Europie — serce Łodzi pełne kawiarni, galerii i murali.",
  },
  {
    id: "mock-lodz-3",
    place_name: "EC1 Łódź",
    category: "museum",
    city: "Łódź",
    address: "ul. Targowa 1/3, 90-022 Łódź",
    latitude: 51.7778,
    longitude: 19.4638,
    rating: 4.5,
    photo_url: pic("ec1-power-plant-museum"),
    vibe_tags: ["nauka", "interaktywnie", "przemysł"],
    description: "Centrum nauki i techniki w zabytkowej elektrowni — planetarium, wystawy i historia industrialnej Łodzi.",
  },
  {
    id: "mock-lodz-4",
    place_name: "OFF Piotrkowska",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska 138/140, 90-062 Łódź",
    latitude: 51.7534,
    longitude: 19.4584,
    rating: 4.6,
    photo_url: pic("off-piotrkowska-courtyard"),
    vibe_tags: ["klimat", "alternatywnie", "food trucks"],
    description: "Kreatywny podwórzec z barami, restauracjami i food truckami — ulubione miejsce łódzkiej bohemy.",
  },
  {
    id: "mock-lodz-5",
    place_name: "Muzeum Sztuki ms2",
    category: "museum",
    city: "Łódź",
    address: "ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7742,
    longitude: 19.4524,
    rating: 4.4,
    photo_url: pic("modern-art-gallery-white"),
    vibe_tags: ["sztuka", "awangarda", "kultura"],
    description: "Jedno z najstarszych muzeów sztuki nowoczesnej na świecie — kolekcja awangardy w budynku Manufaktury.",
  },
  {
    id: "mock-lodz-6",
    place_name: "Centralne Muzeum Włókiennictwa",
    category: "museum",
    city: "Łódź",
    address: "ul. Piotrkowska 282, 93-034 Łódź",
    latitude: 51.7289,
    longitude: 19.4621,
    rating: 4.3,
    photo_url: pic("textile-museum-weaving"),
    vibe_tags: ["historia", "przemysł", "tkaniny"],
    description: "Jedyne takie muzeum w Polsce — historia łódzkiego przemysłu tekstylnego w zabytkowej fabryce.",
  },
  {
    id: "mock-lodz-7",
    place_name: "Pałac Herbsta",
    category: "monument",
    city: "Łódź",
    address: "ul. Przędzalniana 72, 90-338 Łódź",
    latitude: 51.7621,
    longitude: 19.4203,
    rating: 4.5,
    photo_url: pic("herbst-palace-lodz"),
    vibe_tags: ["pałac", "historia", "ogród"],
    description: "Neorenesansowy pałac łódzkiego przemysłowca z oryginalnym wyposażeniem i pięknym ogrodem.",
  },
  {
    id: "mock-lodz-8",
    place_name: "Księży Młyn",
    category: "experience",
    city: "Łódź",
    address: "ul. Przędzalniana 72, 90-338 Łódź",
    latitude: 51.7580,
    longitude: 19.4903,
    rating: 4.4,
    photo_url: pic("ksiezy-mlyn-factory-complex"),
    vibe_tags: ["industrialne", "historia", "mural"],
    description: "Zabytkowy kompleks fabryczno-mieszkalny z XIX w. — dziś siedziba artystów i pracowni twórczych.",
  },
  {
    id: "mock-lodz-9",
    place_name: "Kawiarnia Przędza",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska 17, 90-406 Łódź",
    latitude: 51.7701,
    longitude: 19.4556,
    rating: 4.6,
    photo_url: pic("cafe-interior-warm-light"),
    vibe_tags: ["kawa", "klimat", "slow"],
    description: "Przytulna kawiarnia w kamienicy przy Piotrkowskiej — domowe wypieki i świetna kawa specialty.",
  },
  {
    id: "mock-lodz-10",
    place_name: "Piekarnia Zatorska",
    category: "cafe",
    city: "Łódź",
    address: "ul. Zachodnia 58, 91-066 Łódź",
    latitude: 51.7762,
    longitude: 19.4508,
    rating: 4.7,
    photo_url: pic("artisan-bakery-bread"),
    vibe_tags: ["pieczywo", "śniadanie", "rzemieślnicze"],
    description: "Rzemieślnicza piekarnia z chlebem na zakwasie, rogalami i śniadaniami — kolejki już od rana.",
  },
  {
    id: "mock-lodz-11",
    place_name: "Restauracja Polska Różana",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Gdańska 14, 90-101 Łódź",
    latitude: 51.7620,
    longitude: 19.4558,
    rating: 4.5,
    photo_url: pic("polish-restaurant-interior"),
    vibe_tags: ["polska kuchnia", "tradycja", "obiad"],
    description: "Elegancka restauracja z polską kuchnią — pierogi, żurek i bigos w pięknym XIX-wiecznym wnętrzu.",
  },
  {
    id: "mock-lodz-12",
    place_name: "Łódź Kaliska",
    category: "bar",
    city: "Łódź",
    address: "al. Jaracza 1, 90-252 Łódź",
    latitude: 51.7513,
    longitude: 19.4573,
    rating: 4.3,
    photo_url: pic("pub-bar-night-city"),
    vibe_tags: ["pub", "wieczór", "koncerty"],
    description: "Legendarny łódzki pub — scena dla lokalnych muzyków, szeroki wybór piw i studencki klimat.",
  },
  {
    id: "mock-lodz-13",
    place_name: "Park Źródliska",
    category: "park",
    city: "Łódź",
    address: "ul. Sterlinga, 90-451 Łódź",
    latitude: 51.7564,
    longitude: 19.4497,
    rating: 4.4,
    photo_url: pic("urban-park-pond-ducks"),
    vibe_tags: ["spacer", "relaks", "staw"],
    description: "Zabytkowy park w centrum miasta ze stawem, rzeźbami i zielenią — oaza spokoju wśród kamienic.",
  },
  {
    id: "mock-lodz-14",
    place_name: "Park im. Mickiewicza",
    category: "park",
    city: "Łódź",
    address: "al. Mickiewicza, 90-443 Łódź",
    latitude: 51.7490,
    longitude: 19.4480,
    rating: 4.3,
    photo_url: pic("city-park-path-trees"),
    vibe_tags: ["spacer", "natura", "jogging"],
    description: "Rozległy park na południu śródmieścia — popularne miejsce porannych biegów i niedzielnych spacerów.",
  },
  {
    id: "mock-lodz-15",
    place_name: "Orientarium ZOO Łódź",
    category: "experience",
    city: "Łódź",
    address: "ul. Konstantynowska 8/10, 94-303 Łódź",
    latitude: 51.7732,
    longitude: 19.3942,
    rating: 4.7,
    photo_url: pic("zoo-tropical-exhibit"),
    vibe_tags: ["zwierzęta", "rodzinnie", "egzotycznie"],
    description: "Największe akwarium-terrarium w Polsce z oceanarium i strefą tropikalną — must-see dla każdego.",
  },
  {
    id: "mock-lodz-16",
    place_name: "Szszpilki Bar",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska 85, 90-001 Łódź",
    latitude: 51.7611,
    longitude: 19.4556,
    rating: 4.4,
    photo_url: pic("cocktail-bar-dim-light"),
    vibe_tags: ["koktajle", "wieczór", "klimat"],
    description: "Koktajlowy bar przy Piotrkowskiej — kreatywne drinki i świetna muzyka do późnych godzin.",
  },
  {
    id: "mock-lodz-17",
    place_name: "Hala Bałucki Rynek",
    category: "market",
    city: "Łódź",
    address: "pl. Kościelny 1, 91-131 Łódź",
    latitude: 51.7798,
    longitude: 19.4581,
    rating: 4.2,
    photo_url: pic("outdoor-market-stalls"),
    vibe_tags: ["targ", "lokalnie", "warzywa"],
    description: "Tradycyjny targ Bałucki z lokalnym produktami — warzywa, owoce i polskie przetwory.",
  },
  {
    id: "mock-lodz-18",
    place_name: "Łódź Film School (PWSFTViT)",
    category: "monument",
    city: "Łódź",
    address: "ul. Targowa 61/63, 90-323 Łódź",
    latitude: 51.7680,
    longitude: 19.4735,
    rating: 4.5,
    photo_url: pic("film-school-cinema-building"),
    vibe_tags: ["film", "kultura", "architektura"],
    description: "Słynna Szkoła Filmowa — alma mater Polańskiego, Kieślowskiego i Wajdy. Pokazy i wystawy otwarte dla publiczności.",
  },
  {
    id: "mock-lodz-19",
    place_name: "Śniadania u Oli",
    category: "cafe",
    city: "Łódź",
    address: "ul. 6 Sierpnia 3, 90-001 Łódź",
    latitude: 51.7553,
    longitude: 19.4540,
    rating: 4.6,
    photo_url: pic("breakfast-cafe-eggs-avocado"),
    vibe_tags: ["śniadanie", "brunch", "domowo"],
    description: "Kameralne miejsce na śniadanie i brunch — jajka benedykt, owsianki i świeże soki wyciskane.",
  },
  {
    id: "mock-lodz-20",
    place_name: "Dom Literatury",
    category: "experience",
    city: "Łódź",
    address: "ul. Roosevelta 17, 90-056 Łódź",
    latitude: 51.7674,
    longitude: 19.4596,
    rating: 4.3,
    photo_url: pic("book-library-interior"),
    vibe_tags: ["literatura", "spotkania", "kultura"],
    description: "Kulturalny dom z kawiarnią literacką, spotkaniami autorskimi i niezależną księgarnią.",
  },

  // ── Kawiarnia Testowa (business profile demo) ────────────────────────────────
  {
    id: "mock-krakow-biznes-1",
    place_name: "Kawiarnia Testowa",
    category: "cafe",
    city: "Kraków",
    address: "Rynek Główny 1, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9373,
    rating: 4.7,
    photo_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    vibe_tags: ["kawa", "klimat", "slow"],
    description: "Najlepsza kawiarnia w Krakowie. Świetne espresso i domowe ciasta.",
    businessLogoUrl: "", // pusty string = pokaż orb placeholder
    businessEventTitle: "Happy hour 16:00–18:00, drinki 1+1",
    galleryPhotos: [
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
      "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80",
    ],
  },
];

export const MOCK_BUSINESS_POSTS = [
  {
    id: "mock-post-1",
    description: "Właśnie wjechała nowa karta sezonowa ☕ Latte z lawendą i macha cold brew — dostępne od dziś!",
    photo_urls: ["https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80"],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(), // 3h temu
  },
  {
    id: "mock-post-2",
    description: "Happy hour dziś od 16:00 do 18:00 — wszystkie drinki w cenie 1+1. Zapraszamy! 🎉",
    photo_urls: [],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 dni temu
  },
];

export function getMockPlaces(city: string): MockPlace[] {
  const cityLower = city.toLowerCase();
  return MOCK_PLACES.filter(p => p.city.toLowerCase() === cityLower);
}

export const MOCK_PLACE_DETAIL = {
  formatted_address: "ul. Przykładowa 1, Kraków",
  formatted_phone_number: "+48 12 345 67 89",
  opening_hours: {
    weekday_text: [
      "poniedziałek: 9:00–20:00",
      "wtorek: 9:00–20:00",
      "środa: 9:00–20:00",
      "czwartek: 9:00–20:00",
      "piątek: 9:00–21:00",
      "sobota: 10:00–21:00",
      "niedziela: 10:00–18:00",
    ],
    open_now: true,
  },
  rating: 4.5,
  user_ratings_total: 1234,
  website: "https://example.com",
  photos: [],
  reviews: [
    {
      author_name: "Anna K.",
      rating: 5,
      text: "Świetne miejsce, bardzo polecam! Byłam tu kilka razy i zawsze super.",
      relative_time_description: "tydzień temu",
    },
    {
      author_name: "Marek W.",
      rating: 4,
      text: "Dobre miejsce na popołudniowy spacer. Miło spędzony czas.",
      relative_time_description: "2 tygodnie temu",
    },
  ],
};
