import type { MockPlace } from "@/components/plan-wizard/PlaceSwiper";

export const MOCK_MODE = true; // TODO: zmień na false przed launche'm

// Free deterministic photos — no API key, no billing
const pic = (seed: string) => `https://picsum.photos/seed/${seed}/800/600`;

export const MOCK_PLACES: MockPlace[] = [
  // ── Kraków ──────────────────────────────────────────────────────────────────
  {
    id: "mock-krakow-1",
    place_name: "Wawel",
    category: "monument",
    city: "Kraków",
    address: "Wawel 5, 31-001 Kraków",
    latitude: 50.0543,
    longitude: 19.9352,
    rating: 4.8,
    photo_url: pic("wawel-castle"),
    vibe_tags: ["historia", "widok", "must-see"],
    description: "Królewski zamek na wzgórzu z katedrą, smoczą jaskinią i skarbcem koronnym.",
  },
  {
    id: "mock-krakow-2",
    place_name: "Sukiennice",
    category: "market",
    city: "Kraków",
    address: "Rynek Główny 1, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9373,
    rating: 4.6,
    photo_url: pic("krakow-market"),
    vibe_tags: ["zakupy", "centrum", "pamiątki"],
    description: "Renesansowa hala targowa w sercu Rynku Głównego, pełna kramów z polskim rękodzielnictwem.",
  },
  {
    id: "mock-krakow-3",
    place_name: "Kawiarnia Płyś",
    category: "cafe",
    city: "Kraków",
    address: "ul. Floriańska 12, 31-021 Kraków",
    latitude: 50.0610,
    longitude: 19.9360,
    rating: 4.5,
    photo_url: pic("cozy-cafe-interior"),
    vibe_tags: ["kawa", "klimat", "slow"],
    description: "Kultowa krakowska kawiarnia ze świetną kawą i domowymi ciastkami.",
  },
  {
    id: "mock-krakow-4",
    place_name: "MOCAK",
    category: "museum",
    city: "Kraków",
    address: "ul. Lipowa 4, 30-702 Kraków",
    latitude: 50.0519,
    longitude: 19.9601,
    rating: 4.4,
    photo_url: pic("modern-art-museum"),
    vibe_tags: ["sztuka", "kultura", "współczesność"],
    description: "Muzeum Sztuki Współczesnej w Krakowie — prowokujące wystawy w dawnej fabryce Schindlera.",
  },
  {
    id: "mock-krakow-5",
    place_name: "Kazimierz",
    category: "experience",
    city: "Kraków",
    address: "Kazimierz, 31-056 Kraków",
    latitude: 50.0517,
    longitude: 19.9431,
    rating: 4.7,
    photo_url: pic("kazimierz-krakow"),
    vibe_tags: ["klimat", "bary", "historia"],
    description: "Historyczna żydowska dzielnica pełna galerii, barów i klimatycznych podwórek.",
  },
  {
    id: "mock-krakow-6",
    place_name: "Planty",
    category: "park",
    city: "Kraków",
    address: "Park Planty, Kraków",
    latitude: 50.0597,
    longitude: 19.9375,
    rating: 4.6,
    photo_url: pic("city-park-green"),
    vibe_tags: ["spacer", "relaks", "natura"],
    description: "Pierścień zieleni okalający Stare Miasto — idealne miejsce na poranny spacer.",
  },
  {
    id: "mock-krakow-7",
    place_name: "Kościół Mariacki",
    category: "monument",
    city: "Kraków",
    address: "pl. Mariacki 5, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9390,
    rating: 4.8,
    photo_url: pic("gothic-church-tower"),
    vibe_tags: ["architektura", "historia", "ołtarz Wita Stwosza"],
    description: "Gotycka bazylika z XIV w. z hejnałem i słynnym ołtarzem Wita Stwosza.",
  },
  {
    id: "mock-krakow-8",
    place_name: "Veganico",
    category: "restaurant",
    city: "Kraków",
    address: "ul. Sławkowska 8, 31-014 Kraków",
    latitude: 50.0618,
    longitude: 19.9350,
    rating: 4.5,
    photo_url: pic("vegan-restaurant-food"),
    vibe_tags: ["vege", "zdrowe", "lunch"],
    description: "Wegańska restauracja w centrum — kolorowe miski i smoothie, idealne na lunch.",
  },
  {
    id: "mock-krakow-9",
    place_name: "Hala Targowa Stary Kleparz",
    category: "market",
    city: "Kraków",
    address: "ul. Krowoderska 22, 31-141 Kraków",
    latitude: 50.0672,
    longitude: 19.9390,
    rating: 4.3,
    photo_url: pic("local-food-market"),
    vibe_tags: ["lokalnie", "śniadanie", "warzywa"],
    description: "Jeden z najstarszych targów w Krakowie — świeże produkty od lokalnych rolników.",
  },
  {
    id: "mock-krakow-10",
    place_name: "Bar Mleczny Centralny",
    category: "restaurant",
    city: "Kraków",
    address: "ul. Jagiellońska 1, 31-010 Kraków",
    latitude: 50.0628,
    longitude: 19.9362,
    rating: 4.2,
    photo_url: pic("polish-milk-bar"),
    vibe_tags: ["tanie jedzenie", "nostalgiczny", "klasyk"],
    description: "Kultowy bar mleczny z czasów PRL — pierogi, żurek i kompot w niebiciu cenach.",
  },
  {
    id: "mock-krakow-11",
    place_name: "Muzeum Narodowe",
    category: "museum",
    city: "Kraków",
    address: "al. 3 Maja 1, 30-062 Kraków",
    latitude: 50.0587,
    longitude: 19.9262,
    rating: 4.5,
    photo_url: pic("national-museum-art"),
    vibe_tags: ["sztuka", "kultura", "malarstwo"],
    description: "Największe muzeum w Polsce z bogatą kolekcją polskiego malarstwa i rzemiosła.",
  },
  {
    id: "mock-krakow-12",
    place_name: "Forum Przestrzenie",
    category: "bar",
    city: "Kraków",
    address: "ul. Marii Konopnickiej 28, 30-302 Kraków",
    latitude: 50.0521,
    longitude: 19.9358,
    rating: 4.4,
    photo_url: pic("riverside-bar-terrace"),
    vibe_tags: ["taras", "Wisła", "koktajle"],
    description: "Bar na tarasie dawnego hotelu Forum z zapierającym widokiem na Wisłę i Wawel.",
  },
  // ── Warszawa ─────────────────────────────────────────────────────────────────
  {
    id: "mock-warszawa-1",
    place_name: "Stare Miasto",
    category: "monument",
    city: "Warszawa",
    address: "Stare Miasto, 00-272 Warszawa",
    latitude: 52.2497,
    longitude: 21.0122,
    rating: 4.6,
    photo_url: pic("warsaw-old-town"),
    vibe_tags: ["historia", "spacer", "odbudowane"],
    description: "Pięknie odbudowane Stare Miasto wpisane na listę UNESCO.",
  },
  {
    id: "mock-warszawa-2",
    place_name: "Centrum Nauki Kopernik",
    category: "experience",
    city: "Warszawa",
    address: "Wybrzeże Kościuszkowskie 20, 00-390 Warszawa",
    latitude: 52.2415,
    longitude: 21.0281,
    rating: 4.7,
    photo_url: pic("science-center-exhibit"),
    vibe_tags: ["nauka", "interaktywnie", "dla wszystkich"],
    description: "Interaktywne muzeum nauki z setkami eksponatów do samodzielnego odkrywania.",
  },
  {
    id: "mock-warszawa-3",
    place_name: "Hala Koszyki",
    category: "restaurant",
    city: "Warszawa",
    address: "ul. Koszykowa 63, 02-008 Warszawa",
    latitude: 52.2227,
    longitude: 21.0157,
    rating: 4.5,
    photo_url: pic("food-hall-indoor"),
    vibe_tags: ["food hall", "różnorodność", "lunch"],
    description: "Zabytkowa hala targowa zamieniona w modne miejsce z kuchnią z całego świata.",
  },
  // ── Gdańsk ───────────────────────────────────────────────────────────────────
  {
    id: "mock-gdansk-1",
    place_name: "Długi Targ",
    category: "viewpoint",
    city: "Gdańsk",
    address: "Długi Targ, 80-827 Gdańsk",
    latitude: 54.3490,
    longitude: 18.6531,
    rating: 4.7,
    photo_url: pic("gdansk-harbor-street"),
    vibe_tags: ["widok", "kamienice", "centrum"],
    description: "Reprezentacyjna ulica Gdańska z Fontanną Neptuna i Dworem Artusa.",
  },
  {
    id: "mock-gdansk-2",
    place_name: "Muzeum II Wojny Światowej",
    category: "museum",
    city: "Gdańsk",
    address: "pl. Władysława Bartoszewskiego 1, 80-862 Gdańsk",
    latitude: 54.3565,
    longitude: 18.6508,
    rating: 4.8,
    photo_url: pic("war-museum-exhibition"),
    vibe_tags: ["historia", "poruszające", "must-see"],
    description: "Jedno z najważniejszych muzeów historycznych w Europie — poruszająca narracja o wojnie.",
  },
  // ── Wrocław ──────────────────────────────────────────────────────────────────
  {
    id: "mock-wroclaw-1",
    place_name: "Ostrów Tumski",
    category: "monument",
    city: "Wrocław",
    address: "Ostrów Tumski, 50-329 Wrocław",
    latitude: 51.1147,
    longitude: 17.0463,
    rating: 4.7,
    photo_url: pic("cathedral-island-river"),
    vibe_tags: ["katedra", "most", "wieczór"],
    description: "Historyczna wyspa z katedrą — magiczne miejsce szczególnie po zmierzchu.",
  },
  {
    id: "mock-wroclaw-2",
    place_name: "Hala Stulecia",
    category: "experience",
    city: "Wrocław",
    address: "ul. Wystawowa 1, 51-618 Wrocław",
    latitude: 51.1071,
    longitude: 17.0774,
    rating: 4.5,
    photo_url: pic("historic-dome-building"),
    vibe_tags: ["architektura", "UNESCO", "events"],
    description: "Modernistyczna hala z 1913 r. wpisana na listę UNESCO — ikona wrocławskiej architektury.",
  },

  // ── Kawiarnia Testowa (business profile demo) ────────────────────────────────
  {
    id: "mock-krakow-biznes-1",
    place_name: "Kawiarnia Testowa",
    category: "cafe",
    city: "Kraków",
    address: "Rynek Główny 1, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9373,
    rating: 4.7,
    photo_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    vibe_tags: ["kawa", "klimat", "slow"],
    description: "Najlepsza kawiarnia w Krakowie. Świetne espresso i domowe ciasta.",
    businessLogoUrl: "", // pusty string = pokaż orb placeholder
    businessEventTitle: "Happy hour 16:00–18:00, drinki 1+1",
  },
];

export function getMockPlaces(city: string): MockPlace[] {
  const cityLower = city.toLowerCase();
  return MOCK_PLACES.filter(p => p.city.toLowerCase() === cityLower);
}

export const MOCK_PLACE_DETAIL = {
  formatted_address: "ul. Przykładowa 1, Kraków",
  formatted_phone_number: "+48 12 345 67 89",
  opening_hours: {
    weekday_text: [
      "poniedziałek: 9:00–20:00",
      "wtorek: 9:00–20:00",
      "środa: 9:00–20:00",
      "czwartek: 9:00–20:00",
      "piątek: 9:00–21:00",
      "sobota: 10:00–21:00",
      "niedziela: 10:00–18:00",
    ],
    open_now: true,
  },
  rating: 4.5,
  user_ratings_total: 1234,
  website: "https://example.com",
  photos: [],
  reviews: [
    {
      author_name: "Anna K.",
      rating: 5,
      text: "Świetne miejsce, bardzo polecam! Byłam tu kilka razy i zawsze super.",
      relative_time_description: "tydzień temu",
    },
    {
      author_name: "Marek W.",
      rating: 4,
      text: "Dobre miejsce na popołudniowy spacer. Miło spędzony czas.",
      relative_time_description: "2 tygodnie temu",
    },
  ],
};
