import type { MockPlace } from "@/components/plan-wizard/PlaceSwiper";

export const MOCK_MODE = true; // TODO: zmień na false przed launche'm

// Free deterministic photos — no API key, no billing
const pic = (seed: string) => `https://picsum.photos/seed/${seed}/800/600`;

export const MOCK_PLACES: MockPlace[] = [
  // ── Kraków ──────────────────────────────────────────────────────────────────
  {
    id: "mock-krakow-1",
    place_name: "Wawel",
    category: "monument",
    city: "Kraków",
    address: "Wawel 5, 31-001 Kraków",
    latitude: 50.0543,
    longitude: 19.9352,
    rating: 4.8,
    photo_url: pic("wawel-castle"),
    vibe_tags: ["historia", "widok", "must-see"],
    description: "Królewski zamek na wzgórzu z katedrą, smoczą jaskinią i skarbcem koronnym.",
  },
  {
    id: "mock-krakow-2",
    place_name: "Sukiennice",
    category: "market",
    city: "Kraków",
    address: "Rynek Główny 1, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9373,
    rating: 4.6,
    photo_url: pic("krakow-market"),
    vibe_tags: ["zakupy", "centrum", "pamiątki"],
    description: "Renesansowa hala targowa w sercu Rynku Głównego, pełna kramów z polskim rękodzielnictwem.",
  },
  {
    id: "mock-krakow-3",
    place_name: "Kawiarnia Płyś",
    category: "cafe",
    city: "Kraków",
    address: "ul. Floriańska 12, 31-021 Kraków",
    latitude: 50.0610,
    longitude: 19.9360,
    rating: 4.5,
    photo_url: pic("cozy-cafe-interior"),
    vibe_tags: ["kawa", "klimat", "slow"],
    description: "Kultowa krakowska kawiarnia ze świetną kawą i domowymi ciastkami.",
  },
  {
    id: "mock-krakow-4",
    place_name: "MOCAK",
    category: "museum",
    city: "Kraków",
    address: "ul. Lipowa 4, 30-702 Kraków",
    latitude: 50.0519,
    longitude: 19.9601,
    rating: 4.4,
    photo_url: pic("modern-art-museum"),
    vibe_tags: ["sztuka", "kultura", "współczesność"],
    description: "Muzeum Sztuki Współczesnej w Krakowie — prowokujące wystawy w dawnej fabryce Schindlera.",
  },
  {
    id: "mock-krakow-5",
    place_name: "Kazimierz",
    category: "experience",
    city: "Kraków",
    address: "Kazimierz, 31-056 Kraków",
    latitude: 50.0517,
    longitude: 19.9431,
    rating: 4.7,
    photo_url: pic("kazimierz-krakow"),
    vibe_tags: ["klimat", "bary", "historia"],
    description: "Historyczna żydowska dzielnica pełna galerii, barów i klimatycznych podwórek.",
  },
  {
    id: "mock-krakow-6",
    place_name: "Planty",
    category: "park",
    city: "Kraków",
    address: "Park Planty, Kraków",
    latitude: 50.0597,
    longitude: 19.9375,
    rating: 4.6,
    photo_url: pic("city-park-green"),
    vibe_tags: ["spacer", "relaks", "natura"],
    description: "Pierścień zieleni okalający Stare Miasto — idealne miejsce na poranny spacer.",
  },
  {
    id: "mock-krakow-7",
    place_name: "Kościół Mariacki",
    category: "monument",
    city: "Kraków",
    address: "pl. Mariacki 5, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9390,
    rating: 4.8,
    photo_url: pic("gothic-church-tower"),
    vibe_tags: ["architektura", "historia", "ołtarz Wita Stwosza"],
    description: "Gotycka bazylika z XIV w. z hejnałem i słynnym ołtarzem Wita Stwosza.",
  },
  {
    id: "mock-krakow-8",
    place_name: "Veganico",
    category: "restaurant",
    city: "Kraków",
    address: "ul. Sławkowska 8, 31-014 Kraków",
    latitude: 50.0618,
    longitude: 19.9350,
    rating: 4.5,
    photo_url: pic("vegan-restaurant-food"),
    vibe_tags: ["vege", "zdrowe", "lunch"],
    description: "Wegańska restauracja w centrum — kolorowe miski i smoothie, idealne na lunch.",
  },
  {
    id: "mock-krakow-9",
    place_name: "Hala Targowa Stary Kleparz",
    category: "market",
    city: "Kraków",
    address: "ul. Krowoderska 22, 31-141 Kraków",
    latitude: 50.0672,
    longitude: 19.9390,
    rating: 4.3,
    photo_url: pic("local-food-market"),
    vibe_tags: ["lokalnie", "śniadanie", "warzywa"],
    description: "Jeden z najstarszych targów w Krakowie — świeże produkty od lokalnych rolników.",
  },
  {
    id: "mock-krakow-10",
    place_name: "Bar Mleczny Centralny",
    category: "restaurant",
    city: "Kraków",
    address: "ul. Jagiellońska 1, 31-010 Kraków",
    latitude: 50.0628,
    longitude: 19.9362,
    rating: 4.2,
    photo_url: pic("polish-milk-bar"),
    vibe_tags: ["tanie jedzenie", "nostalgiczny", "klasyk"],
    description: "Kultowy bar mleczny z czasów PRL — pierogi, żurek i kompot w niebiciu cenach.",
  },
  {
    id: "mock-krakow-11",
    place_name: "Muzeum Narodowe",
    category: "museum",
    city: "Kraków",
    address: "al. 3 Maja 1, 30-062 Kraków",
    latitude: 50.0587,
    longitude: 19.9262,
    rating: 4.5,
    photo_url: pic("national-museum-art"),
    vibe_tags: ["sztuka", "kultura", "malarstwo"],
    description: "Największe muzeum w Polsce z bogatą kolekcją polskiego malarstwa i rzemiosła.",
  },
  {
    id: "mock-krakow-12",
    place_name: "Forum Przestrzenie",
    category: "bar",
    city: "Kraków",
    address: "ul. Marii Konopnickiej 28, 30-302 Kraków",
    latitude: 50.0521,
    longitude: 19.9358,
    rating: 4.4,
    photo_url: pic("riverside-bar-terrace"),
    vibe_tags: ["taras", "Wisła", "koktajle"],
    description: "Bar na tarasie dawnego hotelu Forum z zapierającym widokiem na Wisłę i Wawel.",
  },
  // ── Warszawa ─────────────────────────────────────────────────────────────────
  {
    id: "mock-warszawa-1",
    place_name: "Stare Miasto",
    category: "monument",
    city: "Warszawa",
    address: "Stare Miasto, 00-272 Warszawa",
    latitude: 52.2497,
    longitude: 21.0122,
    rating: 4.6,
    photo_url: pic("warsaw-old-town"),
    vibe_tags: ["historia", "spacer", "odbudowane"],
    description: "Pięknie odbudowane Stare Miasto wpisane na listę UNESCO.",
  },
  {
    id: "mock-warszawa-2",
    place_name: "Centrum Nauki Kopernik",
    category: "experience",
    city: "Warszawa",
    address: "Wybrzeże Kościuszkowskie 20, 00-390 Warszawa",
    latitude: 52.2415,
    longitude: 21.0281,
    rating: 4.7,
    photo_url: pic("science-center-exhibit"),
    vibe_tags: ["nauka", "interaktywnie", "dla wszystkich"],
    description: "Interaktywne muzeum nauki z setkami eksponatów do samodzielnego odkrywania.",
  },
  {
    id: "mock-warszawa-3",
    place_name: "Hala Koszyki",
    category: "restaurant",
    city: "Warszawa",
    address: "ul. Koszykowa 63, 02-008 Warszawa",
    latitude: 52.2227,
    longitude: 21.0157,
    rating: 4.5,
    photo_url: pic("food-hall-indoor"),
    vibe_tags: ["food hall", "różnorodność", "lunch"],
    description: "Zabytkowa hala targowa zamieniona w modne miejsce z kuchnią z całego świata.",
  },
  // ── Gdańsk ───────────────────────────────────────────────────────────────────
  {
    id: "mock-gdansk-1",
    place_name: "Długi Targ",
    category: "viewpoint",
    city: "Gdańsk",
    address: "Długi Targ, 80-827 Gdańsk",
    latitude: 54.3490,
    longitude: 18.6531,
    rating: 4.7,
    photo_url: pic("gdansk-harbor-street"),
    vibe_tags: ["widok", "kamienice", "centrum"],
    description: "Reprezentacyjna ulica Gdańska z Fontanną Neptuna i Dworem Artusa.",
  },
  {
    id: "mock-gdansk-2",
    place_name: "Muzeum II Wojny Światowej",
    category: "museum",
    city: "Gdańsk",
    address: "pl. Władysława Bartoszewskiego 1, 80-862 Gdańsk",
    latitude: 54.3565,
    longitude: 18.6508,
    rating: 4.8,
    photo_url: pic("war-museum-exhibition"),
    vibe_tags: ["historia", "poruszające", "must-see"],
    description: "Jedno z najważniejszych muzeów historycznych w Europie — poruszająca narracja o wojnie.",
  },
  // ── Wrocław ──────────────────────────────────────────────────────────────────
  {
    id: "mock-wroclaw-1",
    place_name: "Ostrów Tumski",
    category: "monument",
    city: "Wrocław",
    address: "Ostrów Tumski, 50-329 Wrocław",
    latitude: 51.1147,
    longitude: 17.0463,
    rating: 4.7,
    photo_url: pic("cathedral-island-river"),
    vibe_tags: ["katedra", "most", "wieczór"],
    description: "Historyczna wyspa z katedrą — magiczne miejsce szczególnie po zmierzchu.",
  },
  {
    id: "mock-wroclaw-2",
    place_name: "Hala Stulecia",
    category: "experience",
    city: "Wrocław",
    address: "ul. Wystawowa 1, 51-618 Wrocław",
    latitude: 51.1071,
    longitude: 17.0774,
    rating: 4.5,
    photo_url: pic("historic-dome-building"),
    vibe_tags: ["architektura", "UNESCO", "events"],
    description: "Modernistyczna hala z 1913 r. wpisana na listę UNESCO — ikona wrocławskiej architektury.",
  },

  // ── Łódź ─────────────────────────────────────────────────────────────────────
  // Kawiarnie
  {
    id: "mock-lodz-1",
    place_name: "The Brick Coffee Factory",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7612,
    longitude: 19.4578,
    rating: 4.6,
    photo_url: pic("brick-coffee-industrial"),
    vibe_tags: ["specialty coffee", "industrialne", "klimat"],
    description: "Kawiarnia specialty w klimatycznym industrialnym wnętrzu — pourover, aeropress i świetne espresso.",
  },
  {
    id: "mock-lodz-2",
    place_name: "Przędza",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska 17, 90-406 Łódź",
    latitude: 51.7701,
    longitude: 19.4556,
    rating: 4.6,
    photo_url: pic("cozy-cafe-warm-light"),
    vibe_tags: ["kawa", "klimat", "slow"],
    description: "Kameralna kawiarnia przy Piotrkowskiej — przytulna atmosfera, lokalne wypieki i pyszna kawa.",
  },
  {
    id: "mock-lodz-3",
    place_name: "Tubajka",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7540,
    longitude: 19.4541,
    rating: 4.4,
    photo_url: pic("neighborhood-cafe-lodge"),
    vibe_tags: ["sąsiedzka", "kawa", "wyluzowany"],
    description: "Lubiana kawiarnia sąsiedzka z dobrą kawą i domowym klimatem — stałe bywalczynie wracają co dzień.",
  },
  {
    id: "mock-lodz-4",
    place_name: "Pijalnia Czekolady E.Wedel",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska 80, 90-001 Łódź",
    latitude: 51.7609,
    longitude: 19.4558,
    rating: 4.5,
    photo_url: pic("hot-chocolate-wedel"),
    vibe_tags: ["czekolada", "słodkości", "klasyk"],
    description: "Kultowa pijalnia gorącej czekolady — legendarny wedlowski wyrób w eleganckiej oprawie.",
  },
  {
    id: "mock-lodz-5",
    place_name: "Fit Cake Łódź Księży Młyn",
    category: "cafe",
    city: "Łódź",
    address: "ul. Przędzalniana, 90-338 Łódź",
    latitude: 51.7574,
    longitude: 19.4908,
    rating: 4.4,
    photo_url: pic("healthy-cake-cafe"),
    vibe_tags: ["fit", "zdrowe ciasta", "słodkości"],
    description: "Cukiernia ze zdrowymi ciastami i tortami bez cukru — idealna dla dbających o sylwetkę.",
  },
  {
    id: "mock-lodz-6",
    place_name: "The White Bear Coffee",
    category: "cafe",
    city: "Łódź",
    address: "ul. Traugutta, 90-001 Łódź",
    latitude: 51.7652,
    longitude: 19.4555,
    rating: 4.6,
    photo_url: pic("white-bear-specialty-coffee"),
    vibe_tags: ["specialty coffee", "flat white", "matcha"],
    description: "Przytulna kawiarnia specialty z autentyczną pasją do kawy — świetny flat white i matcha latte.",
  },
  {
    id: "mock-lodz-7",
    place_name: "Szykier Coffee & Bistro",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7634,
    longitude: 19.4560,
    rating: 4.5,
    photo_url: pic("coffee-bistro-interior"),
    vibe_tags: ["kawa", "bistro", "śniadanie"],
    description: "Kawiarnia z bistro menu — dobra kawa, awokado toast i domowe lemoniady.",
  },
  {
    id: "mock-lodz-8",
    place_name: "Grand Café",
    category: "cafe",
    city: "Łódź",
    address: "ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7760,
    longitude: 19.4490,
    rating: 4.5,
    photo_url: pic("grand-cafe-manufaktura"),
    vibe_tags: ["elegancja", "Manufaktura", "klimat"],
    description: "Elegancka kawiarnia w przestrzeni Manufaktury — szeroka karta napojów i ciast w pięknym wnętrzu.",
  },
  {
    id: "mock-lodz-9",
    place_name: "Klubokawiarnia Owoce i Warzywa",
    category: "cafe",
    city: "Łódź",
    address: "ul. Roosevelta, 90-056 Łódź",
    latitude: 51.7580,
    longitude: 19.4602,
    rating: 4.5,
    photo_url: pic("club-cafe-eclectic"),
    vibe_tags: ["alternatywnie", "kultura", "eventy"],
    description: "Kultowe łódzkie miejsce — kawiarnia, bar i przestrzeń kulturalna w jednym, pełna eventów.",
  },
  {
    id: "mock-lodz-10",
    place_name: "Chatka Ech",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7571,
    longitude: 19.4587,
    rating: 4.4,
    photo_url: pic("tiny-cozy-cafe"),
    vibe_tags: ["przytulnie", "kawa", "domowo"],
    description: "Malutka przytulna kawiarnia z domowym klimatem — doskonałe miejsce do pracy i spotkań.",
  },
  {
    id: "mock-lodz-11",
    place_name: "Costa Coffee",
    category: "cafe",
    city: "Łódź",
    address: "Manufaktura, ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7775,
    longitude: 19.4475,
    rating: 4.1,
    photo_url: pic("costa-coffee-chain"),
    vibe_tags: ["sieciowa", "kawa", "Manufaktura"],
    description: "Sieciowa kawiarnia w Manufakturze — niezawodna kawa i szeroki wybór napojów.",
  },
  {
    id: "mock-lodz-12",
    place_name: "Starbucks",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7609,
    longitude: 19.4556,
    rating: 4.0,
    photo_url: pic("starbucks-cafe-city"),
    vibe_tags: ["sieciowa", "kawa", "znana marka"],
    description: "Globalna sieć kawiarni z szerokim menu napojów, w samym centrum Piotrkowskiej.",
  },
  {
    id: "mock-lodz-13",
    place_name: "Coffeehood",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7625,
    longitude: 19.4560,
    rating: 4.5,
    photo_url: pic("coffeehood-specialty"),
    vibe_tags: ["specialty coffee", "neighborhood", "kawa"],
    description: "Kawiarnia specialty z wybranymi ziarnami — świadoma kawa i miła obsługa.",
  },
  {
    id: "mock-lodz-14",
    place_name: "Podkawa Palarnia Kawy",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7591,
    longitude: 19.4570,
    rating: 4.6,
    photo_url: pic("coffee-roastery-bags"),
    vibe_tags: ["palarnia", "specialty", "origin"],
    description: "Palarnia kawy z serwisem na miejscu — świeżo palona kawa z całego świata i degustacje.",
  },
  {
    id: "mock-lodz-15",
    place_name: "Kraftowa",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7615,
    longitude: 19.4572,
    rating: 4.4,
    photo_url: pic("craft-cafe-bar"),
    vibe_tags: ["kraftowa", "craft", "alternatywnie"],
    description: "Kawiarnia i craft bar w jednym — selektywne ziarna i piwa kraftowe.",
  },
  {
    id: "mock-lodz-16",
    place_name: "Coffee to Go",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7602,
    longitude: 19.4553,
    rating: 4.2,
    photo_url: pic("coffee-takeaway-cup"),
    vibe_tags: ["na wynos", "szybko", "kawa"],
    description: "Ekspresowa kawa na wynos dla pracowitych łodzian — dobra jakość, niska cena.",
  },
  {
    id: "mock-lodz-17",
    place_name: "Ola! de Nata",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7598,
    longitude: 19.4548,
    rating: 4.6,
    photo_url: pic("pastel-de-nata-portuguese"),
    vibe_tags: ["pastel de nata", "portugalia", "słodkości"],
    description: "Kawiarnia z autentycznymi pastéis de nata — chrupiące ciastka z kremem i espresso.",
  },
  {
    id: "mock-lodz-18",
    place_name: "Kubek Coffee & Matcha & Gofry",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7620,
    longitude: 19.4565,
    rating: 4.5,
    photo_url: pic("matcha-waffles-cafe"),
    vibe_tags: ["matcha", "gofry", "specialty"],
    description: "Kawiarnia specialty z matchą i goframi — idealne na popołudniową przerwę.",
  },
  {
    id: "mock-lodz-19",
    place_name: "Café Book&Cook",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7630,
    longitude: 19.4560,
    rating: 4.5,
    photo_url: pic("bookshop-cafe-shelves"),
    vibe_tags: ["książki", "kawa", "atmosfera"],
    description: "Kawiarnia połączona z księgarnią — spotkaj się przy kawie z dobrą książką.",
  },
  {
    id: "mock-lodz-20",
    place_name: "Kawiarnia Magazyn Kawy",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7645,
    longitude: 19.4557,
    rating: 4.6,
    photo_url: pic("coffee-warehouse-specialty"),
    vibe_tags: ["magazyn", "specialty", "kawa"],
    description: "Kawiarnia specialty w klimacie magazynu — świeże ziarna i precyzyjne parzenie.",
  },
  {
    id: "mock-lodz-21",
    place_name: "Hot Air Cafe",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7607,
    longitude: 19.4543,
    rating: 4.4,
    photo_url: pic("hot-air-balloon-cafe"),
    vibe_tags: ["balon", "klimat", "kawa"],
    description: "Kawiarnia z motywem balonów na gorące powietrze — kolorowa przestrzeń i dobra kawa.",
  },
  {
    id: "mock-lodz-22",
    place_name: "Pan tu nie stał - cafe bar",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7618,
    longitude: 19.4551,
    rating: 4.4,
    photo_url: pic("cafe-bar-evening-city"),
    vibe_tags: ["café bar", "wieczorami", "klimat"],
    description: "Klimatyczny café bar przy Piotrkowskiej — kawy, koktajle i muzyczne eventy wieczorami.",
  },
  {
    id: "mock-lodz-23",
    place_name: "PAJ",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7560,
    longitude: 19.4590,
    rating: 4.4,
    photo_url: pic("paj-cafe-pastry"),
    vibe_tags: ["kawa", "ciasta", "spokój"],
    description: "Kameralna kawiarnia z domowymi ciastami — urokliwe wnętrze i doskonała kawa.",
  },
  {
    id: "mock-lodz-24",
    place_name: "KIOSK",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7680,
    longitude: 19.4555,
    rating: 4.3,
    photo_url: pic("kiosk-retro-coffee"),
    vibe_tags: ["kiosk", "retro", "kawa"],
    description: "Kawiarnia w klimacie kiosku — nostalgiczny PRL połączony z nowoczesną kawą specialty.",
  },
  {
    id: "mock-lodz-25",
    place_name: "Koleżanki Cafe",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7571,
    longitude: 19.4580,
    rating: 4.5,
    photo_url: pic("friends-cafe-cozy"),
    vibe_tags: ["przyjacielsko", "kawa", "domowe ciasta"],
    description: "Kawiarnia dla przyjaciółek i nie tylko — gościnne wnętrze i rozgrzewająca atmosfera.",
  },
  {
    id: "mock-lodz-26",
    place_name: "FAVE Izabela Stręk",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7655,
    longitude: 19.4555,
    rating: 4.6,
    photo_url: pic("design-specialty-cafe"),
    vibe_tags: ["design", "specialty", "wyjątkowe"],
    description: "Designerska kawiarnia z autorską koncepcją — kawa specialty i wypieki w pięknej przestrzeni.",
  },
  {
    id: "mock-lodz-27",
    place_name: "HYT - pracownia baristyczna",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7593,
    longitude: 19.4560,
    rating: 4.6,
    photo_url: pic("barista-workshop-coffee"),
    vibe_tags: ["baristyczna", "specialty", "warsztaty"],
    description: "Pracownia baristyczna z kursami i parzeniem na miejscu — tu kawa to nauka i pasja.",
  },
  {
    id: "mock-lodz-28",
    place_name: "Qubek Cafe",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7620,
    longitude: 19.4548,
    rating: 4.3,
    photo_url: pic("qubek-cafe-simple"),
    vibe_tags: ["kawa", "spokój", "centrum"],
    description: "Kameralna kawiarnia w centrum — dobra kawa i przyjazna obsługa w cichym wnętrzu.",
  },
  {
    id: "mock-lodz-29",
    place_name: "Vita Cafe",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7640,
    longitude: 19.4560,
    rating: 4.4,
    photo_url: pic("healthy-cafe-bowls"),
    vibe_tags: ["zdrowo", "kawa", "soki"],
    description: "Kawiarnia zdrowotna z kawą, świeżymi sokami i bowlami — idealna na zdrowy start dnia.",
  },
  {
    id: "mock-lodz-30",
    place_name: "Kawiarnia Ekspres do kawy KROKUSOWA",
    category: "cafe",
    city: "Łódź",
    address: "ul. Krokusowa, Łódź",
    latitude: 51.7680,
    longitude: 19.4070,
    rating: 4.2,
    photo_url: pic("local-neighborhood-coffee"),
    vibe_tags: ["ekspresowo", "sąsiedzka", "kawa"],
    description: "Lokalna kawiarnia osiedlowa — szybka kawa i miła obsługa tuż przy domu.",
  },
  {
    id: "mock-lodz-31",
    place_name: "Cafe Verte",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7610,
    longitude: 19.4564,
    rating: 4.4,
    photo_url: pic("green-plants-cafe"),
    vibe_tags: ["zielono", "relaks", "kawa"],
    description: "Kawiarnia z zielonymi akcentami i roślinami — odprężająca atmosfera do spotkań i pracy.",
  },
  {
    id: "mock-lodz-32",
    place_name: "Prosto z Mostu klubokawiarnia",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7592,
    longitude: 19.4553,
    rating: 4.4,
    photo_url: pic("club-cafe-culture"),
    vibe_tags: ["klub", "kultura", "kawa"],
    description: "Kawiarnia-klub z wydarzeniami kulturalnymi — od porannej kawy po wieczorne koncerty.",
  },
  {
    id: "mock-lodz-33",
    place_name: "KAWIARNIA EKSPRES DO KAWY",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7703,
    longitude: 19.4558,
    rating: 4.2,
    photo_url: pic("classic-cafe-espresso"),
    vibe_tags: ["ekspresowo", "klasyczna", "kawa"],
    description: "Klasyczna kawiarnia z szybką obsługą — espresso, herbata i domowe ciasto.",
  },
  {
    id: "mock-lodz-34",
    place_name: "Karmello Chocolatier",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7618,
    longitude: 19.4559,
    rating: 4.6,
    photo_url: pic("chocolate-pralines-shop"),
    vibe_tags: ["czekolada", "pralinki", "słodkości"],
    description: "Czekoladownia z ręcznie robionymi pralinkami i gorącą czekoladą — raj dla miłośników kakao.",
  },
  {
    id: "mock-lodz-35",
    place_name: "Mono Cafe & Bistro",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7633,
    longitude: 19.4561,
    rating: 4.4,
    photo_url: pic("minimalist-cafe-bistro"),
    vibe_tags: ["minimalistycznie", "bistro", "kawa"],
    description: "Minimalistyczna kawiarnia i bistro w jednym — dobra kawa, lekkie dania i spokój.",
  },
  {
    id: "mock-lodz-36",
    place_name: "Empatia Sweet",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7599,
    longitude: 19.4548,
    rating: 4.4,
    photo_url: pic("sweet-bakery-cafe"),
    vibe_tags: ["słodkości", "ciasta", "domowo"],
    description: "Kawiarnia cukiernicza z domowymi wypiekami — idealna na słodką przerwę w ciągu dnia.",
  },
  // Piekarnie
  {
    id: "mock-lodz-37",
    place_name: "Montag",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7625,
    longitude: 19.4568,
    rating: 4.7,
    photo_url: pic("artisan-sourdough-bakery"),
    vibe_tags: ["piekarnia", "zakwas", "śniadanie"],
    description: "Rzemieślnicza piekarnia z chlebem na zakwasie i rogalami — tu każdy poranek jest dobry.",
  },
  {
    id: "mock-lodz-38",
    place_name: "Receptura cukiernia/piekarnia",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7601,
    longitude: 19.4556,
    rating: 4.5,
    photo_url: pic("patisserie-cakes-display"),
    vibe_tags: ["cukiernia", "piekarnia", "rzemieślnicze"],
    description: "Piekarnia i cukiernia z autorską recepturą — świeże bułki, torty na zamówienie.",
  },
  {
    id: "mock-lodz-39",
    place_name: "OKRUCHY mikropiekarnia",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7612,
    longitude: 19.4582,
    rating: 4.6,
    photo_url: pic("micro-bakery-bread-loaf"),
    vibe_tags: ["mikropiekarnia", "zakwas", "rzemieślnicze"],
    description: "Mała rzemieślnicza piekarnia z duszą — każda bułka i bochen to ręcznie wyrabiane dzieło.",
  },
  {
    id: "mock-lodz-40",
    place_name: "La Polacco - Piekarnia & Cukiernia",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7580,
    longitude: 19.4563,
    rating: 4.5,
    photo_url: pic("italian-bakery-croissant"),
    vibe_tags: ["włoskie", "croissanty", "kawa"],
    description: "Piekarnia w stylu włoskim — rogale, focaccia i espresso w środku Łodzi.",
  },
  {
    id: "mock-lodz-41",
    place_name: "Gorący Precel F-Wiatrak",
    category: "cafe",
    city: "Łódź",
    address: "ul. Wiatrakowa, Łódź",
    latitude: 51.7700,
    longitude: 19.4212,
    rating: 4.3,
    photo_url: pic("hot-pretzel-bakery"),
    vibe_tags: ["precel", "szybko", "sól"],
    description: "Kultowe precle z solą prosto z pieca — łódzka klasyka na szybkie wzmocnienie podczas spaceru.",
  },
  {
    id: "mock-lodz-42",
    place_name: "Piekarz Cake & Coffee",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7623,
    longitude: 19.4571,
    rating: 4.4,
    photo_url: pic("bakery-cake-coffee-shop"),
    vibe_tags: ["ciasta", "kawa", "piekarnia"],
    description: "Lokalna piekarnia z dorodnymi ciastami i świeżą kawą — idealne miejsce na przerwę.",
  },
  {
    id: "mock-lodz-43",
    place_name: "Pan Precel",
    category: "cafe",
    city: "Łódź",
    address: "Manufaktura, ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7765,
    longitude: 19.4473,
    rating: 4.3,
    photo_url: pic("pretzel-kiosk-market"),
    vibe_tags: ["precel", "klasyk", "szybko"],
    description: "Piekarnio-kiosk z gorącymi preclami w Manufakturze — pyszna przekąska podczas zwiedzania.",
  },
  // Śniadania
  {
    id: "mock-lodz-44",
    place_name: "Caffe przy ulicy - Śródmieście",
    category: "cafe",
    city: "Łódź",
    address: "Śródmieście, Łódź",
    latitude: 51.7615,
    longitude: 19.4555,
    rating: 4.5,
    photo_url: pic("breakfast-cafe-city-center"),
    vibe_tags: ["śniadanie", "centrum", "codziennie"],
    description: "Popularne miejsce śniadaniowe w centrum — jajka na różne sposoby, granola i świeże soki.",
  },
  {
    id: "mock-lodz-45",
    place_name: "Caffe przy ulicy - Bałuty",
    category: "cafe",
    city: "Łódź",
    address: "Bałuty, Łódź",
    latitude: 51.7870,
    longitude: 19.4562,
    rating: 4.4,
    photo_url: pic("local-breakfast-cafe"),
    vibe_tags: ["śniadanie", "Bałuty", "sąsiedzkie"],
    description: "Lokalna kawiarnia śniadaniowa na Bałutach — domowe wypieki i rodzinna atmosfera.",
  },
  {
    id: "mock-lodz-46",
    place_name: "Caffe przy ulicy - Retkinia",
    category: "cafe",
    city: "Łódź",
    address: "Retkinia, Łódź",
    latitude: 51.7610,
    longitude: 19.3860,
    rating: 4.4,
    photo_url: pic("morning-cafe-retkinia"),
    vibe_tags: ["śniadanie", "Retkinia", "codziennie"],
    description: "Przyjazna kawiarnia śniadaniowa w Retkini — idealna na poranne spotkanie przed pracą.",
  },
  {
    id: "mock-lodz-47",
    place_name: "CHAŁKA I MASŁO",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7583,
    longitude: 19.4578,
    rating: 4.6,
    photo_url: pic("challah-bread-butter-breakfast"),
    vibe_tags: ["śniadanie", "chałka", "domowo"],
    description: "Łódzki śniadaniowy must-visit — świeże chałki, masło i jajka w pysznych zestawach.",
  },
  {
    id: "mock-lodz-48",
    place_name: "Breadnia",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7602,
    longitude: 19.4560,
    rating: 4.5,
    photo_url: pic("bread-bakery-breakfast-bar"),
    vibe_tags: ["chleb", "śniadanie", "rzemieślnicze"],
    description: "Piekarnia śniadaniowa z wypiekami na zakwasie i kawą specialty — tu chleb jest gwiazdą.",
  },
  {
    id: "mock-lodz-49",
    place_name: "Bułkę przez Bibułkę",
    category: "cafe",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7630,
    longitude: 19.4552,
    rating: 4.5,
    photo_url: pic("buns-breakfast-stylish"),
    vibe_tags: ["bułki", "śniadanie", "styl"],
    description: "Urocze miejsce ze świeżymi bułkami i kawą — stylowe wnętrze i śniadanie ustawiające na cały dzień.",
  },
  {
    id: "mock-lodz-50",
    place_name: "MORNING coffee & more (Dąbrowa)",
    category: "cafe",
    city: "Łódź",
    address: "Dąbrowa, Łódź",
    latitude: 51.7680,
    longitude: 19.3990,
    rating: 4.5,
    photo_url: pic("morning-coffee-breakfast"),
    vibe_tags: ["poranny", "kawa", "Dąbrowa"],
    description: "Kawiarnia poranna na Dąbrowie — dobra kawa, szybkie śniadanie i miła obsługa.",
  },
  {
    id: "mock-lodz-51",
    place_name: "MORNING coffee & more (Polesie)",
    category: "cafe",
    city: "Łódź",
    address: "Polesie, Łódź",
    latitude: 51.7592,
    longitude: 19.4263,
    rating: 4.5,
    photo_url: pic("morning-coffee-polesie"),
    vibe_tags: ["poranny", "kawa", "Polesie"],
    description: "Siostrany lokal na Polesiu — te same dobre poranki i śniadania w innej części miasta.",
  },
  // Restauracje
  {
    id: "mock-lodz-52",
    place_name: "FaBuła Bistro",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7604,
    longitude: 19.4547,
    rating: 4.5,
    photo_url: pic("modern-bistro-seasonal"),
    vibe_tags: ["bistro", "nowoczesne", "lunch"],
    description: "Nowoczesne bistro z sezonowym menu — świeże lokalne składniki w kreatywnych kompozycjach.",
  },
  {
    id: "mock-lodz-53",
    place_name: "Manekin",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7771,
    longitude: 19.4476,
    rating: 4.4,
    photo_url: pic("crepe-restaurant-pancakes"),
    vibe_tags: ["naleśniki", "Manufaktura", "różnorodne"],
    description: "Popularna restauracja specjalizująca się w naleśnikach i krêpach — słodkie i słone nadzienia.",
  },
  {
    id: "mock-lodz-54",
    place_name: "Pierogarnia Stary Młyn",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7598,
    longitude: 19.4558,
    rating: 4.5,
    photo_url: pic("pierogi-polish-dumplings"),
    vibe_tags: ["pierogi", "polska kuchnia", "tradycja"],
    description: "Pierogarnia z ogromnym wyborem pierogów — ruskie, z mięsem, z owocami i w sosach.",
  },
  {
    id: "mock-lodz-55",
    place_name: "Whiskey in the Jar",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7625,
    longitude: 19.4554,
    rating: 4.4,
    photo_url: pic("whiskey-pub-bar"),
    vibe_tags: ["whiskey", "pub", "burger"],
    description: "Pub z szeroką kolekcją whisky i dobrymi burgerami — wieczorowe miejsce dla miłośników trunków.",
  },
  {
    id: "mock-lodz-56",
    place_name: "Ristorante Mare e Monti",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7582,
    longitude: 19.4561,
    rating: 4.5,
    photo_url: pic("italian-seafood-restaurant"),
    vibe_tags: ["włoskie", "owoce morza", "pasta"],
    description: "Włoska restauracja Mare e Monti — świeże owoce morza i pasta w eleganckim wydaniu.",
  },
  {
    id: "mock-lodz-57",
    place_name: "ANATEWKA",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7619,
    longitude: 19.4553,
    rating: 4.6,
    photo_url: pic("jewish-polish-restaurant"),
    vibe_tags: ["żydowska kuchnia", "klimat", "tradycja"],
    description: "Restauracja z kuchnią żydowsko-polską — czulent, gęsie pipki i klimat dawnej Łodzi.",
  },
  {
    id: "mock-lodz-58",
    place_name: "Ato Ramen",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7607,
    longitude: 19.4560,
    rating: 4.6,
    photo_url: pic("ramen-japanese-noodles"),
    vibe_tags: ["ramen", "japońskie", "umami"],
    description: "Autentyczne ramen z długo gotowanymi bulionami — tonkotsu, miso i shoyu.",
  },
  {
    id: "mock-lodz-59",
    place_name: "Galicja",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7614,
    longitude: 19.4563,
    rating: 4.4,
    photo_url: pic("galician-cuisine-restaurant"),
    vibe_tags: ["galicyjska kuchnia", "tradycja", "obiad"],
    description: "Restauracja z kuchnią galicyjską — smaki kresów w ciepłym, gościnnym wnętrzu.",
  },
  {
    id: "mock-lodz-60",
    place_name: "Aloha by Las Palmas",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7590,
    longitude: 19.4548,
    rating: 4.4,
    photo_url: pic("hawaiian-poke-bowl"),
    vibe_tags: ["hawajskie", "poke bowl", "egzotycznie"],
    description: "Poke bowle i hawajska kuchnia — kolorowe, zdrowe i pełne egzotycznych smaków.",
  },
  {
    id: "mock-lodz-61",
    place_name: "Imber",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7601,
    longitude: 19.4549,
    rating: 4.5,
    photo_url: pic("ginger-modern-restaurant"),
    vibe_tags: ["imbir", "nowoczesne", "sezonowe"],
    description: "Nowoczesna restauracja z sezonowym menu i lokalnymi składnikami.",
  },
  {
    id: "mock-lodz-62",
    place_name: "Otwarte Drzwi",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7620,
    longitude: 19.4557,
    rating: 4.4,
    photo_url: pic("homestyle-restaurant-lunch"),
    vibe_tags: ["otwarte", "serdeczne", "lunch"],
    description: "Przytulna restauracja z codziennym lunchowym menu — jak u znajomych, zawsze serdecznie.",
  },
  {
    id: "mock-lodz-63",
    place_name: "Al Dente Pasta & Bąble Bar",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7608,
    longitude: 19.4554,
    rating: 4.5,
    photo_url: pic("pasta-italian-wine-bar"),
    vibe_tags: ["pasta", "włoskie", "wino"],
    description: "Restauracja z włoską pastą i bąblami — świeże tagliatelle i dobrze dobrane wino.",
  },
  {
    id: "mock-lodz-64",
    place_name: "Złoty Imbir",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7635,
    longitude: 19.4561,
    rating: 4.4,
    photo_url: pic("asian-fusion-restaurant"),
    vibe_tags: ["azjatyckie", "imbir", "fusion"],
    description: "Restauracja azjatycka z wietnamskimi, tajskimi i chińskimi smakami w centrum Łodzi.",
  },
  {
    id: "mock-lodz-65",
    place_name: "Wolność Neo Bistro",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska 138, 90-062 Łódź",
    latitude: 51.7534,
    longitude: 19.4572,
    rating: 4.6,
    photo_url: pic("neo-bistro-natural-wine"),
    vibe_tags: ["neo bistro", "naturalne wino", "sezonowe"],
    description: "Neo bistro przy OFF Piotrkowskiej — sezonowe menu, naturalne wino i swobodna atmosfera.",
  },
  {
    id: "mock-lodz-66",
    place_name: "Ato Sushi",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7605,
    longitude: 19.4558,
    rating: 4.5,
    photo_url: pic("sushi-japanese-rolls"),
    vibe_tags: ["sushi", "japońskie", "świeże"],
    description: "Sushiarnia z autentycznymi japońskimi rolkami — świeże ryby i sake.",
  },
  {
    id: "mock-lodz-67",
    place_name: "Bawełna - Restauracja Manufaktura",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7768,
    longitude: 19.4471,
    rating: 4.4,
    photo_url: pic("cotton-restaurant-manufaktura"),
    vibe_tags: ["Manufaktura", "polska kuchnia", "historia"],
    description: "Restauracja w sercu Manufaktury nawiązująca do historii łódzkiego przemysłu bawełnianego.",
  },
  {
    id: "mock-lodz-68",
    place_name: "Lavash - Restauracja Gruzińska i Ormiańska",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7612,
    longitude: 19.4561,
    rating: 4.6,
    photo_url: pic("georgian-armenian-khachapuri"),
    vibe_tags: ["gruzińska", "chaczapuri", "Kaukaz"],
    description: "Restauracja z kuchnią gruzińską i ormiańską — chaczapuri, chinkali i skarby kaukaskie.",
  },
  {
    id: "mock-lodz-69",
    place_name: "Señoritas Restaurant & Lounge",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7598,
    longitude: 19.4545,
    rating: 4.3,
    photo_url: pic("mexican-latin-restaurant"),
    vibe_tags: ["meksykańskie", "lounge", "margarita"],
    description: "Meksykańsko-latynoska restauracja z kolorowymi drinkami i pełnym menu.",
  },
  {
    id: "mock-lodz-70",
    place_name: "Susharnia",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7617,
    longitude: 19.4556,
    rating: 4.4,
    photo_url: pic("sushi-bar-lodz"),
    vibe_tags: ["sushi", "azjatyckie", "przystępne ceny"],
    description: "Popularna łódzka sushiarnia — bogata karta rolki i sashimi w przystępnych cenach.",
  },
  {
    id: "mock-lodz-71",
    place_name: "Tango Argentino Steakhouse",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7628,
    longitude: 19.4563,
    rating: 4.5,
    photo_url: pic("argentinian-steakhouse-meat"),
    vibe_tags: ["argentyńskie", "steak", "mięso"],
    description: "Steakhouse inspirowany argentyńską tradycją — wyśmienite steki i empanadas.",
  },
  {
    id: "mock-lodz-72",
    place_name: "Restauracja Roma",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7583,
    longitude: 19.4569,
    rating: 4.3,
    photo_url: pic("italian-pizza-wood-oven"),
    vibe_tags: ["włoskie", "pizza", "tiramisu"],
    description: "Klasyczna włoska restauracja — pizza w drewnianym piecu i świeże makrony.",
  },
  {
    id: "mock-lodz-73",
    place_name: "Tawerna Pepe Verde",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7614,
    longitude: 19.4551,
    rating: 4.3,
    photo_url: pic("mediterranean-taverna"),
    vibe_tags: ["śródziemnomorskie", "tawerna", "wino"],
    description: "Śródziemnomorska tawerna z selekcją win i tapasami — morskie klimaty w centrum Łodzi.",
  },
  {
    id: "mock-lodz-74",
    place_name: "Trattoria Italiana",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7607,
    longitude: 19.4549,
    rating: 4.4,
    photo_url: pic("trattoria-italian-food"),
    vibe_tags: ["włoskie", "trattoria", "autentyczne"],
    description: "Autentyczna trattoria z włoskim chlebem, makaronami i antipasti.",
  },
  {
    id: "mock-lodz-75",
    place_name: "Winni",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7632,
    longitude: 19.4558,
    rating: 4.4,
    photo_url: pic("wine-bistro-natural"),
    vibe_tags: ["wino", "bistro", "lekkie dania"],
    description: "Winna restauracja z naturalnymi winami i lekkimi daniami dopasowanymi do trunku.",
  },
  {
    id: "mock-lodz-76",
    place_name: "Len i Bawełna - OFF Piotrkowska",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska 138/140, 90-062 Łódź",
    latitude: 51.7534,
    longitude: 19.4584,
    rating: 4.5,
    photo_url: pic("off-piotrkowska-restaurant"),
    vibe_tags: ["OFF Piotrkowska", "sezonowe", "industrialne"],
    description: "Restauracja w sercu OFF Piotrkowskiej — kreatywna kuchnia sezonowa w klimatycznym wnętrzu.",
  },
  {
    id: "mock-lodz-77",
    place_name: "Ukryte Rzeki",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7595,
    longitude: 19.4560,
    rating: 4.6,
    photo_url: pic("hidden-rivers-restaurant"),
    vibe_tags: ["fusion", "intymnie", "odkrycie"],
    description: "Elegancka restauracja fusion skryta przed turystami — wyjątkowe menu i intymna atmosfera.",
  },
  {
    id: "mock-lodz-78",
    place_name: "Hot Spoon",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7609,
    longitude: 19.4543,
    rating: 4.3,
    photo_url: pic("soup-restaurant-hot"),
    vibe_tags: ["zupy", "rozgrzewające", "lunch"],
    description: "Restauracja specjalizująca się w zupach — od żurku po egzotyczne curry z całego świata.",
  },
  {
    id: "mock-lodz-79",
    place_name: "Pizzeria Osiedlowa - Chojny",
    category: "restaurant",
    city: "Łódź",
    address: "Chojny, Łódź",
    latitude: 51.7190,
    longitude: 19.4670,
    rating: 4.4,
    photo_url: pic("neighborhood-pizza-chojny"),
    vibe_tags: ["pizza", "osiedlowo", "Chojny"],
    description: "Osiedlowa pizzeria na Chojnach — domowe miejsce z pyszną pizzą i życzliwą obsługą.",
  },
  {
    id: "mock-lodz-80",
    place_name: "Pizzeria Osiedlowa - Centrum",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7609,
    longitude: 19.4557,
    rating: 4.3,
    photo_url: pic("pizza-burger-restaurant"),
    vibe_tags: ["pizza", "burger", "centrum"],
    description: "Pizza i burgery w centrum — klasyczne połączenie w dobrej cenie.",
  },
  {
    id: "mock-lodz-81",
    place_name: "Restauracja Laxmi Indyjska",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7604,
    longitude: 19.4554,
    rating: 4.5,
    photo_url: pic("indian-curry-restaurant"),
    vibe_tags: ["indyjska", "curry", "egzotyczne"],
    description: "Autentyczna restauracja indyjska — kuchnia subkontynentu od delikatnych po pikantne curry.",
  },
  {
    id: "mock-lodz-82",
    place_name: "Restauracja Piwnica Łódzka",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7621,
    longitude: 19.4560,
    rating: 4.4,
    photo_url: pic("cellar-polish-restaurant"),
    vibe_tags: ["piwnica", "polska kuchnia", "tradycja"],
    description: "Restauracja w piwnicy łódzkiej kamienicy — kuchnia polska z atmosferą starego miasta.",
  },
  {
    id: "mock-lodz-83",
    place_name: "King Kong Thai Food",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7598,
    longitude: 19.4548,
    rating: 4.5,
    photo_url: pic("thai-food-restaurant"),
    vibe_tags: ["tajska", "pad thai", "pikantne"],
    description: "Tajska restauracja z autentyczną kuchnią — pad thai, curry i zupy.",
  },
  {
    id: "mock-lodz-84",
    place_name: "Polka",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7615,
    longitude: 19.4560,
    rating: 4.4,
    photo_url: pic("polish-traditional-restaurant"),
    vibe_tags: ["polska kuchnia", "tradycja", "bigos"],
    description: "Restauracja z tradycyjną polską kuchnią — bigos, żurek i pierogi w nowoczesnej aranżacji.",
  },
  {
    id: "mock-lodz-85",
    place_name: "Pierogarnia TEREMOK przy Piramowicza",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piramowicza, Łódź",
    latitude: 51.7671,
    longitude: 19.4551,
    rating: 4.4,
    photo_url: pic("ukrainian-pierogi-teremok"),
    vibe_tags: ["pierogi", "ukraińska", "domowe"],
    description: "Ukraińska pierogarnia przy ul. Piramowicza — warenyky, pierogi i barszcz w ciepłym klimacie.",
  },
  {
    id: "mock-lodz-86",
    place_name: "A tu...TAJ",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7613,
    longitude: 19.4557,
    rating: 4.4,
    photo_url: pic("indian-taj-masala"),
    vibe_tags: ["indyjska", "masala", "tandoor"],
    description: "Restauracja indyjska z szerokim menu — tikka masala, samosy i naan w autentycznej oprawie.",
  },
  {
    id: "mock-lodz-87",
    place_name: "Perlyna Ukrainy",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7607,
    longitude: 19.4562,
    rating: 4.4,
    photo_url: pic("ukrainian-home-cooking"),
    vibe_tags: ["ukraińska", "domowe", "barszcz"],
    description: "Ukraińska restauracja Perła Ukrainy — domowe smaki wschodu, barszcz i pierogi jak u mamy.",
  },
  {
    id: "mock-lodz-88",
    place_name: "Spółdzielnia",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7586,
    longitude: 19.4573,
    rating: 4.4,
    photo_url: pic("cooperative-restaurant-local"),
    vibe_tags: ["spółdzielczo", "lokalni dostawcy", "sezonowe"],
    description: "Restauracja w duchu spółdzielczym — lokalni dostawcy, sezonowe menu i zaangażowanie społeczne.",
  },
  {
    id: "mock-lodz-89",
    place_name: "Restauracja Alpejska - Łódź Górna",
    category: "restaurant",
    city: "Łódź",
    address: "Łódź Górna, Łódź",
    latitude: 51.7150,
    longitude: 19.4740,
    rating: 4.3,
    photo_url: pic("alpine-restaurant-cheese"),
    vibe_tags: ["alpejska", "Łódź Górna", "sery"],
    description: "Restauracja z kuchnią alpejską na południu Łodzi — sery, fondue i górskie klimaty przez cały rok.",
  },
  {
    id: "mock-lodz-90",
    place_name: "Tłusty Śledź - Smażalnia ryb",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7611,
    longitude: 19.4558,
    rating: 4.4,
    photo_url: pic("fish-fry-herring"),
    vibe_tags: ["śledź", "ryby", "smażalnia"],
    description: "Lokalna smażalnia ryb — tłusty śledź, dorsz w tempurze i inne frytowane specjały morskie.",
  },
  {
    id: "mock-lodz-91",
    place_name: "Restauracja Delight",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7618,
    longitude: 19.4554,
    rating: 4.4,
    photo_url: pic("elegant-restaurant-dining"),
    vibe_tags: ["elegancja", "fine dining", "obiad"],
    description: "Elegancka restauracja z ambicją — staranne menu i szczególna dbałość o smak.",
  },
  {
    id: "mock-lodz-92",
    place_name: "Fatamorgana",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7624,
    longitude: 19.4558,
    rating: 4.3,
    photo_url: pic("exotic-atmosphere-restaurant"),
    vibe_tags: ["klimatyczne", "miraż", "egzotycznie"],
    description: "Klimatyczna restauracja z orientalnym akcentem — złudzenie egzotyki w centrum Łodzi.",
  },
  {
    id: "mock-lodz-93",
    place_name: "DOKI Gastrobar",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7595,
    longitude: 19.4560,
    rating: 4.5,
    photo_url: pic("gastrobar-tapas-drinks"),
    vibe_tags: ["gastrobar", "tapas", "nowoczesne"],
    description: "Nowoczesny gastrobar z małymi daniami i szeroką kartą napojów — idealne na wieczór.",
  },
  {
    id: "mock-lodz-94",
    place_name: "Restauracja Ogień i Sól",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7605,
    longitude: 19.4562,
    rating: 4.4,
    photo_url: pic("fire-salt-grill-restaurant"),
    vibe_tags: ["ogień i sól", "grillowane", "klimat"],
    description: "Restauracja z filozofią prostoty — grillowane mięsa i warzywa z solą i ogniem.",
  },
  {
    id: "mock-lodz-95",
    place_name: "Restauracja Manuarte",
    category: "restaurant",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7609,
    longitude: 19.4555,
    rating: 4.5,
    photo_url: pic("art-restaurant-creative"),
    vibe_tags: ["sztuka i jedzenie", "kreatywne", "elegancja"],
    description: "Restauracja łącząca kuchnię z sztuką — każde danie to dzieło, wnętrze jak galeria.",
  },
  // Bary
  {
    id: "mock-lodz-96",
    place_name: "Long Play",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7621,
    longitude: 19.4554,
    rating: 4.5,
    photo_url: pic("vinyl-music-bar"),
    vibe_tags: ["muzyka", "winyle", "bar"],
    description: "Bar dla miłośników winyli i dobrej muzyki — szeroka kolekcja płyt i kraftowe piwa.",
  },
  {
    id: "mock-lodz-97",
    place_name: "Football Pub",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7634,
    longitude: 19.4559,
    rating: 4.2,
    photo_url: pic("sports-pub-screens"),
    vibe_tags: ["piłka nożna", "pub", "mecze"],
    description: "Pub sportowy ze screenami na żywo — idealne miejsce na mecze przy zimnym piwie.",
  },
  {
    id: "mock-lodz-98",
    place_name: "Pijalnia Wódki i Piwa",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7609,
    longitude: 19.4558,
    rating: 4.2,
    photo_url: pic("polish-vodka-bar-prl"),
    vibe_tags: ["wódka", "piwo", "PRL"],
    description: "Sieciowa pijalnia z tradycyjnymi polskimi trunkami — wódka z ogórkiem w PRL-owym klimacie.",
  },
  {
    id: "mock-lodz-99",
    place_name: "Bistro",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7600,
    longitude: 19.4552,
    rating: 4.2,
    photo_url: pic("casual-bistro-bar"),
    vibe_tags: ["bistro", "casual", "drinki"],
    description: "Lokalne bistro z barem — lekkie dania i drinki w przytulnej atmosferze.",
  },
  {
    id: "mock-lodz-100",
    place_name: "Pijana Wiśnia",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7616,
    longitude: 19.4557,
    rating: 4.4,
    photo_url: pic("cherry-nalewka-bar"),
    vibe_tags: ["wiśnia", "nalewki", "klimatyczne"],
    description: "Bar z wiśniowymi nalewkami i koktajlami — słodko-kwaśny klimat i wieczorowe imprezy.",
  },
  {
    id: "mock-lodz-101",
    place_name: "Kij",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7603,
    longitude: 19.4550,
    rating: 4.3,
    photo_url: pic("billiard-bar-evening"),
    vibe_tags: ["bilard", "wieczór", "klimat"],
    description: "Bar z bilardem i dobrą muzyką — klimatyczne miejsce na wieczorne spotkanie.",
  },
  {
    id: "mock-lodz-102",
    place_name: "Czupito",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7612,
    longitude: 19.4555,
    rating: 4.1,
    photo_url: pic("shots-bar-party"),
    vibe_tags: ["shoty", "impreza", "koktajle"],
    description: "Sieciowy bar ze shotami i koktajlami po przystępnych cenach — popularny warm-up przed imprezą.",
  },
  {
    id: "mock-lodz-103",
    place_name: "Pub GALANTA 7",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7628,
    longitude: 19.4563,
    rating: 4.3,
    photo_url: pic("traditional-pub-beer"),
    vibe_tags: ["pub", "piwo rzemieślnicze", "wieczór"],
    description: "Tradycyjny pub przy ulicy — dobre piwo rzemieślnicze i miła atmosfera do rozmowy.",
  },
  {
    id: "mock-lodz-104",
    place_name: "Spaleni Słońcem",
    category: "bar",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7594,
    longitude: 19.4567,
    rating: 4.4,
    photo_url: pic("summer-cocktail-bar"),
    vibe_tags: ["lato", "koktajle", "klimat"],
    description: "Bar z letnim klimatem przez cały rok — koktajle, muzyka i poczucie urlopu.",
  },
  // Muzea
  {
    id: "mock-lodz-105",
    place_name: "Muzeum Pałac Herbsta",
    category: "museum",
    city: "Łódź",
    address: "ul. Przędzalniana 72, 90-338 Łódź",
    latitude: 51.7621,
    longitude: 19.4203,
    rating: 4.5,
    photo_url: pic("herbst-palace-museum"),
    vibe_tags: ["pałac", "sztuka", "XIX wiek"],
    description: "Neorenesansowy pałac łódzkiego fabrykanta z oryginalnym wyposażeniem — oddział Muzeum Sztuki.",
  },
  {
    id: "mock-lodz-106",
    place_name: "Muzeum Kinematografii w Łodzi",
    category: "museum",
    city: "Łódź",
    address: "pl. Zwycięstwa 1, 90-312 Łódź",
    latitude: 51.7773,
    longitude: 19.4543,
    rating: 4.6,
    photo_url: pic("cinema-film-museum"),
    vibe_tags: ["film", "kinematografia", "Polska Szkoła"],
    description: "Jedyne takie muzeum w Polsce — historia kina, Polska Szkoła Filmowa i pamiątki po wielkich reżyserach.",
  },
  {
    id: "mock-lodz-107",
    place_name: "Muzeum Światła Łódź",
    category: "museum",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7613,
    longitude: 19.4568,
    rating: 4.4,
    photo_url: pic("light-museum-interactive"),
    vibe_tags: ["światło", "interaktywnie", "nauka"],
    description: "Interaktywne muzeum poświęcone zjawisku światła — eksperymenty z fotoniką i historią elektryczności.",
  },
  {
    id: "mock-lodz-108",
    place_name: "Planetarium EC1",
    category: "museum",
    city: "Łódź",
    address: "ul. Targowa 1/3, 90-022 Łódź",
    latitude: 51.7778,
    longitude: 19.4638,
    rating: 4.6,
    photo_url: pic("planetarium-dome-stars"),
    vibe_tags: ["planetarium", "gwiazdy", "kosmos"],
    description: "Nowoczesne planetarium w EC1 — cyfrowe seanse o kosmosie i gwiazdach dla całej rodziny.",
  },
  {
    id: "mock-lodz-109",
    place_name: "Centralne Muzeum Włókiennictwa",
    category: "museum",
    city: "Łódź",
    address: "ul. Piotrkowska 282, 93-034 Łódź",
    latitude: 51.7289,
    longitude: 19.4621,
    rating: 4.4,
    photo_url: pic("textile-museum-weaving-loom"),
    vibe_tags: ["włókiennictwo", "tkaniny", "historia przemysłu"],
    description: "Jedyne takie muzeum w Polsce — historia łódzkiego przemysłu tekstylnego z działającymi krosnami.",
  },
  {
    id: "mock-lodz-110",
    place_name: "Stacja Radegast",
    category: "museum",
    city: "Łódź",
    address: "ul. Wojska Polskiego, 91-755 Łódź",
    latitude: 51.7903,
    longitude: 19.4552,
    rating: 4.8,
    photo_url: pic("radegast-station-memorial"),
    vibe_tags: ["Radegast", "getto", "must-see"],
    description: "Poruszający pomnik historii — stacja deportacyjna łódzkiego getta, najważniejsze miejsce pamięci w Polsce.",
  },
  {
    id: "mock-lodz-111",
    place_name: "Muzeum Miasta Łodzi",
    category: "museum",
    city: "Łódź",
    address: "ul. Ogrodowa 15, 91-065 Łódź",
    latitude: 51.7769,
    longitude: 19.4479,
    rating: 4.5,
    photo_url: pic("poznanskiego-palace-museum"),
    vibe_tags: ["muzeum miasta", "pałac", "historia"],
    description: "Muzeum w pałacu Poznańskiego — historia Łodzi i jej przemysłowej świetności w imponujących wnętrzach.",
  },
  {
    id: "mock-lodz-112",
    place_name: "Centrum Nauki i Techniki EC1",
    category: "museum",
    city: "Łódź",
    address: "ul. Targowa 1/3, 90-022 Łódź",
    latitude: 51.7778,
    longitude: 19.4638,
    rating: 4.5,
    photo_url: pic("ec1-science-technology"),
    vibe_tags: ["nauka", "technika", "elektrownia"],
    description: "Centrum nauki w zabytkowej elektrowni EC1 — historia energetyki i interaktywne wystawy techniczne.",
  },
  {
    id: "mock-lodz-113",
    place_name: "Muzeum Sztuki w Łodzi MS1",
    category: "museum",
    city: "Łódź",
    address: "ul. Więckowskiego 36, 90-734 Łódź",
    latitude: 51.7593,
    longitude: 19.4553,
    rating: 4.4,
    photo_url: pic("ms1-avant-garde-art"),
    vibe_tags: ["awangarda", "sztuka", "MS1"],
    description: "Pierwsze muzeum sztuki nowoczesnej w Polsce — kolekcja awangardy z lat 20. XX w. i wystawy współczesne.",
  },
  {
    id: "mock-lodz-114",
    place_name: "Muzeum Fabryki",
    category: "museum",
    city: "Łódź",
    address: "ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7771,
    longitude: 19.4474,
    rating: 4.4,
    photo_url: pic("factory-museum-manufaktura"),
    vibe_tags: ["Manufaktura", "fabryka", "historia robotników"],
    description: "Muzeum w sercu Manufaktury — historia fabryki Poznańskiego i losów łódzkich robotników.",
  },
  {
    id: "mock-lodz-115",
    place_name: "Muzeum Tradycji Niepodległościowych - Radogoszcz",
    category: "museum",
    city: "Łódź",
    address: "ul. Zgierska 147, 91-466 Łódź",
    latitude: 51.8090,
    longitude: 19.4580,
    rating: 4.7,
    photo_url: pic("radogoszcz-prison-memorial"),
    vibe_tags: ["martyrologia", "historia", "must-see"],
    description: "Oddział muzeum w dawnym więzieniu Radogoszcz — miejsce kaźni tysięcy Polaków podczas II wojny.",
  },
  {
    id: "mock-lodz-116",
    place_name: "Zajezdnia Muzealna BRUS",
    category: "museum",
    city: "Łódź",
    address: "ul. Wierzbowa, Łódź",
    latitude: 51.7720,
    longitude: 19.4562,
    rating: 4.3,
    photo_url: pic("tram-depot-museum"),
    vibe_tags: ["tramwaje", "zajezdnia", "transport"],
    description: "Muzeum tramwajów i transportu miejskiego Łodzi — zabytkowe tabory i historia komunikacji.",
  },
  {
    id: "mock-lodz-117",
    place_name: "Centrum Komiksu i Narracji Interaktywnej EC1",
    category: "museum",
    city: "Łódź",
    address: "ul. Targowa 1/3, 90-022 Łódź",
    latitude: 51.7778,
    longitude: 19.4638,
    rating: 4.4,
    photo_url: pic("comic-book-center-interactive"),
    vibe_tags: ["komiks", "interaktywnie", "kreatywnie"],
    description: "Centrum komiksu w EC1 — wystawy, warsztaty i interaktywna narracja dla miłośników graficznej opowieści.",
  },
  {
    id: "mock-lodz-118",
    place_name: "Muzeum Sztuki w Łodzi MS2",
    category: "museum",
    city: "Łódź",
    address: "ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7742,
    longitude: 19.4524,
    rating: 4.5,
    photo_url: pic("ms2-contemporary-art-gallery"),
    vibe_tags: ["sztuka nowoczesna", "MS2", "Manufaktura"],
    description: "Oddział Muzeum Sztuki w Manufakturze — duże sale z wystawami współczesnej sztuki polskiej i światowej.",
  },
  // Parki
  {
    id: "mock-lodz-119",
    place_name: "Orientarium ZOO Łódź",
    category: "park",
    city: "Łódź",
    address: "ul. Konstantynowska 8/10, 94-303 Łódź",
    latitude: 51.7732,
    longitude: 19.3942,
    rating: 4.7,
    photo_url: pic("orientarium-zoo-tropical"),
    vibe_tags: ["zoo", "tropikalnie", "rodzinnie"],
    description: "Największe Orientarium w Polsce — oceanarium, tropikalne wystawy i setki gatunków zwierząt.",
  },
  {
    id: "mock-lodz-120",
    place_name: "Ogród Botaniczny w Łodzi",
    category: "park",
    city: "Łódź",
    address: "ul. Krzemieniecka 36/38, 94-303 Łódź",
    latitude: 51.7566,
    longitude: 19.4040,
    rating: 4.4,
    photo_url: pic("botanical-garden-plants"),
    vibe_tags: ["botaniczny", "rośliny", "relaks"],
    description: "Rozległy ogród botaniczny z kolekcją roślin z całego świata — spacer wśród egzotycznej zieleni.",
  },
  {
    id: "mock-lodz-121",
    place_name: "Park Ocalałych",
    category: "park",
    city: "Łódź",
    address: "ul. Wojska Polskiego, Łódź",
    latitude: 51.7890,
    longitude: 19.4647,
    rating: 4.5,
    photo_url: pic("park-ocalałych-memorial"),
    vibe_tags: ["pamięć", "historia", "spacer"],
    description: "Wyjątkowy park upamiętniający ocalałych z Holokaustu — miejsce refleksji i spokojnych spacerów.",
  },
  {
    id: "mock-lodz-122",
    place_name: "Stawy Jana",
    category: "park",
    city: "Łódź",
    address: "ul. Rzgowska, Łódź",
    latitude: 51.7480,
    longitude: 19.4582,
    rating: 4.4,
    photo_url: pic("ponds-park-nature"),
    vibe_tags: ["stawy", "przyroda", "jogging"],
    description: "Urokliwe stawy z parkiem — popularne miejsce spacerów, joggingu i obserwacji ptaków.",
  },
  {
    id: "mock-lodz-123",
    place_name: "Park im. 1 Maja",
    category: "park",
    city: "Łódź",
    address: "ul. Tuszyńska, Łódź",
    latitude: 51.7490,
    longitude: 19.4490,
    rating: 4.3,
    photo_url: pic("urban-park-alleys"),
    vibe_tags: ["park", "spacer", "relaks"],
    description: "Rozległy park na południu miasta — aleje, ławki i zieleń idealna na odpoczynek.",
  },
  {
    id: "mock-lodz-124",
    place_name: "Park Źródliska",
    category: "park",
    city: "Łódź",
    address: "ul. Sterlinga, 90-451 Łódź",
    latitude: 51.7564,
    longitude: 19.4497,
    rating: 4.4,
    photo_url: pic("park-pond-city-center"),
    vibe_tags: ["staw", "centrum", "relaks"],
    description: "Zabytkowy park w centrum z malowniczym stawem — oaza zieleni wśród łódzkich kamienic.",
  },
  {
    id: "mock-lodz-125",
    place_name: "Park na Młynku",
    category: "park",
    city: "Łódź",
    address: "Łódź",
    latitude: 51.7810,
    longitude: 19.4310,
    rating: 4.3,
    photo_url: pic("park-mlynek-green"),
    vibe_tags: ["młyn", "park", "spacer"],
    description: "Kameralny park przy młynku — zielona enklawa z historycznym charakterem.",
  },
  // Markety
  {
    id: "mock-lodz-126",
    place_name: "Manufaktura",
    category: "market",
    city: "Łódź",
    address: "ul. Drewnowska 58, 91-002 Łódź",
    latitude: 51.7773,
    longitude: 19.4472,
    rating: 4.7,
    photo_url: pic("manufaktura-lodz-complex"),
    vibe_tags: ["must-see", "centrum kultury", "historia"],
    description: "Największe centrum kultury, rozrywki i handlu w Polsce — zabytkowa fabryka Poznańskiego tętniąca życiem.",
  },
  {
    id: "mock-lodz-127",
    place_name: "OFF Piotrkowska",
    category: "market",
    city: "Łódź",
    address: "ul. Piotrkowska 138/140, 90-062 Łódź",
    latitude: 51.7534,
    longitude: 19.4584,
    rating: 4.6,
    photo_url: pic("off-piotrkowska-courtyard-market"),
    vibe_tags: ["alternatywnie", "design", "food trucks"],
    description: "Kreatywne centrum przy Piotrkowskiej — design, muzyka, restauracje i wyjątkowe sklepy w podwórzu.",
  },
  {
    id: "mock-lodz-128",
    place_name: "Nowa Sukcesja",
    category: "market",
    city: "Łódź",
    address: "ul. Kilińskiego 269, 93-106 Łódź",
    latitude: 51.7612,
    longitude: 19.4560,
    rating: 4.2,
    photo_url: pic("shopping-center-modern"),
    vibe_tags: ["centrum handlowe", "nowoczesne", "zakupy"],
    description: "Nowoczesne centrum handlowe w centrum Łodzi — szeroki wybór sklepów i restauracji.",
  },
  {
    id: "mock-lodz-129",
    place_name: "Book Się Rodzi",
    category: "market",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7625,
    longitude: 19.4570,
    rating: 4.5,
    photo_url: pic("book-fair-independent"),
    vibe_tags: ["książki", "targi", "kultura"],
    description: "Targi książek i kultury — miejsce dla miłośników literatury z niezależnymi wydawnictwami.",
  },
  {
    id: "mock-lodz-130",
    place_name: "Silva Rerum",
    category: "market",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7630,
    longitude: 19.4558,
    rating: 4.5,
    photo_url: pic("antique-collectibles-shop"),
    vibe_tags: ["antyki", "wyjątkowe", "kolekcjonerskie"],
    description: "Sklep z antykami, rzadkimi przedmiotami i ciekawostkami — każda wizyta to odkrycie czegoś niezwykłego.",
  },
  {
    id: "mock-lodz-131",
    place_name: "Piotrkowska59",
    category: "market",
    city: "Łódź",
    address: "ul. Piotrkowska 59, 90-001 Łódź",
    latitude: 51.7712,
    longitude: 19.4555,
    rating: 4.4,
    photo_url: pic("design-boutiques-piotrkowska"),
    vibe_tags: ["design", "butiki", "styl"],
    description: "Eklektyczne centrum kulturalno-handlowe przy Piotrkowskiej — lokalni projektanci i niezależne butiki.",
  },
  {
    id: "mock-lodz-132",
    place_name: "Noteka",
    category: "market",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7608,
    longitude: 19.4560,
    rating: 4.5,
    photo_url: pic("stationery-notebooks-shop"),
    vibe_tags: ["papeteria", "notesy", "design"],
    description: "Sklep z wyjątkowymi notesami i artykułami papierniczymi — raj dla miłośników pisania i designu.",
  },
  {
    id: "mock-lodz-133",
    place_name: "Folkstar Łódź",
    category: "market",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7600,
    longitude: 19.4555,
    rating: 4.4,
    photo_url: pic("folk-art-craft-shop"),
    vibe_tags: ["folk", "rękodzieło", "etno"],
    description: "Sklep z etnicznymi i folklorystycznymi wyrobami — kolorowe hafty, ceramika i rękodzieło.",
  },
  // Landmarki
  {
    id: "mock-lodz-134",
    place_name: "Pasaż Róży",
    category: "monument",
    city: "Łódź",
    address: "ul. Piotrkowska 3, 90-406 Łódź",
    latitude: 51.7598,
    longitude: 19.4560,
    rating: 4.7,
    photo_url: pic("rose-passage-mirrors-mosaic"),
    vibe_tags: ["pasaż", "lustra", "must-see"],
    description: "Magiczny pasaż wyłożony kolorowymi mozaikami i lustrami — jedna z najpiękniejszych atrakcji Łodzi.",
  },
  {
    id: "mock-lodz-135",
    place_name: "Cmentarz Żydowski w Łodzi",
    category: "monument",
    city: "Łódź",
    address: "ul. Bracka 40, 91-431 Łódź",
    latitude: 51.7957,
    longitude: 19.4689,
    rating: 4.7,
    photo_url: pic("jewish-cemetery-lodz"),
    vibe_tags: ["historia", "cmentarz żydowski", "must-see"],
    description: "Jeden z największych żydowskich cmentarzy w Europie — unikalna architektura nagrobna i historia.",
  },
  {
    id: "mock-lodz-136",
    place_name: "Księży Młyn",
    category: "monument",
    city: "Łódź",
    address: "ul. Przędzalniana, 90-338 Łódź",
    latitude: 51.7574,
    longitude: 19.4908,
    rating: 4.5,
    photo_url: pic("ksiezy-mlyn-industrial-complex"),
    vibe_tags: ["industrialne", "fabryka", "historia"],
    description: "Zabytkowy kompleks fabryk i domów robotniczych — ostoja łódzkiej historii przemysłowej.",
  },
  {
    id: "mock-lodz-137",
    place_name: "Pałac Karola Poznańskiego",
    category: "monument",
    city: "Łódź",
    address: "ul. Ogrodowa 15, 91-065 Łódź",
    latitude: 51.7769,
    longitude: 19.4479,
    rating: 4.7,
    photo_url: pic("poznanskiego-palace-lodz"),
    vibe_tags: ["pałac", "XIX wiek", "muzeum"],
    description: "Monumentalny pałac łódzkiego króla bawełny — dziś siedziba Muzeum Miasta ze wspaniałymi wnętrzami.",
  },
  {
    id: "mock-lodz-138",
    place_name: "Kamienica Pod Gutenbergiem",
    category: "monument",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7618,
    longitude: 19.4557,
    rating: 4.4,
    photo_url: pic("gutenberg-tenement-secession"),
    vibe_tags: ["architektura", "kamienica", "secesja"],
    description: "Piękna kamienica secesyjna z figurą Gutenberga przy Piotrkowskiej — perełka łódzkiej architektury.",
  },
  {
    id: "mock-lodz-139",
    place_name: "Bazylika Archikatedralna św. Stanisława Kostki",
    category: "monument",
    city: "Łódź",
    address: "ul. ks. I. Skorupki 3, 90-458 Łódź",
    latitude: 51.7772,
    longitude: 19.4555,
    rating: 4.6,
    photo_url: pic("archcathedral-lodz-gothic"),
    vibe_tags: ["katedra", "gotyk", "historia"],
    description: "Gotycka bazylika archikatedralna — główna świątynia Łodzi z imponującym wnętrzem i dzwonnicą.",
  },
  {
    id: "mock-lodz-140",
    place_name: "Fortepian Rubinsteina",
    category: "monument",
    city: "Łódź",
    address: "ul. Piotrkowska 78, 90-001 Łódź",
    latitude: 51.7608,
    longitude: 19.4556,
    rating: 4.5,
    photo_url: pic("rubinstein-piano-monument"),
    vibe_tags: ["Rubinstein", "pomnik", "muzyka"],
    description: "Pomnik w kształcie fortepianu upamiętniający Artura Rubinsteina — słynnego pianistę urodzonego w Łodzi.",
  },
  {
    id: "mock-lodz-141",
    place_name: "Monopolis",
    category: "monument",
    city: "Łódź",
    address: "ul. Kopcińskiego 62, 90-032 Łódź",
    latitude: 51.7620,
    longitude: 19.4475,
    rating: 4.5,
    photo_url: pic("monopolis-revitalized-factory"),
    vibe_tags: ["industrialne", "rewitalizacja", "events"],
    description: "Rewitalizowana przestrzeń po dawnej fabryce wódki monopolowej — biura, restauracje i events.",
  },
  {
    id: "mock-lodz-142",
    place_name: "Litzmannstadt Ghetto",
    category: "monument",
    city: "Łódź",
    address: "Bałuty, Łódź",
    latitude: 51.7950,
    longitude: 19.4660,
    rating: 4.6,
    photo_url: pic("litzmannstadt-ghetto-history"),
    vibe_tags: ["getto", "historia", "pamięć"],
    description: "Historyczne miejsce łódzkiego getta — spacer po dawnych ulicach to lekcja historii i hołd dla ofiar.",
  },
  {
    id: "mock-lodz-143",
    place_name: "Dupa Tuwima",
    category: "monument",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7617,
    longitude: 19.4558,
    rating: 4.6,
    photo_url: pic("tuwima-funny-monument-bench"),
    vibe_tags: ["humor", "Tuwim", "selfie"],
    description: "Kultowy żartobliwy pomnik na ławce przy Piotrkowskiej — siedzisko z napisem, obowiązkowe selfie!",
  },
  {
    id: "mock-lodz-144",
    place_name: "Kaplica Karola Scheiblera",
    category: "monument",
    city: "Łódź",
    address: "ul. Przędzalniana, 90-338 Łódź",
    latitude: 51.7580,
    longitude: 19.4905,
    rating: 4.6,
    photo_url: pic("scheibler-chapel-neogothic"),
    vibe_tags: ["kaplica", "neogotyk", "Scheibler"],
    description: "Neogotycka kaplica mauzoleum Karola Scheiblera — jedno z najpiękniejszych dzieł architektury sepulkralnej.",
  },
  {
    id: "mock-lodz-145",
    place_name: "Mural \"Narodziny Dnia\"",
    category: "monument",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7620,
    longitude: 19.4548,
    rating: 4.5,
    photo_url: pic("narodziny-dnia-mural-lodz"),
    vibe_tags: ["mural", "street art", "Piotrkowska"],
    description: "Jeden z najsłynniejszych murali w Łodzi — gigantyczny obraz przy Piotrkowskiej przyciągający fotografów.",
  },
  // Rozrywka
  {
    id: "mock-lodz-146",
    place_name: "SALTOS park trampolin",
    category: "experience",
    city: "Łódź",
    address: "Łódź",
    latitude: 51.7620,
    longitude: 19.4480,
    rating: 4.5,
    photo_url: pic("trampoline-park-fun"),
    vibe_tags: ["trampoliny", "aktywnie", "rodzinnie"],
    description: "Duży park trampolin — idealne miejsce dla dzieci i dorosłych na skoki i akrobatyki.",
  },
  {
    id: "mock-lodz-147",
    place_name: "Virtual House",
    category: "experience",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7614,
    longitude: 19.4562,
    rating: 4.4,
    photo_url: pic("virtual-reality-vr-gaming"),
    vibe_tags: ["VR", "wirtualna rzeczywistość", "gry"],
    description: "Dom rzeczywistości wirtualnej — hełmy VR i doświadczenia immersyjne przenoszące w inny świat.",
  },
  {
    id: "mock-lodz-148",
    place_name: "RaceSpot - symulatory motorsport",
    category: "experience",
    city: "Łódź",
    address: "Łódź",
    latitude: 51.7601,
    longitude: 19.4550,
    rating: 4.6,
    photo_url: pic("racing-simulator-motorsport"),
    vibe_tags: ["symulatory", "motorsport", "koktajle"],
    description: "Centrum z symulatorami wyścigów, barem koktajlowym i pizzą — dla fanów motoryzacji i zabawy.",
  },
  {
    id: "mock-lodz-149",
    place_name: "Centrum Nauki Experymentarium",
    category: "experience",
    city: "Łódź",
    address: "ul. Ogrodowa 19, 91-065 Łódź",
    latitude: 51.7785,
    longitude: 19.4475,
    rating: 4.5,
    photo_url: pic("science-experiments-center"),
    vibe_tags: ["nauka", "eksperymenty", "interaktywnie"],
    description: "Centrum nauki z setkami interaktywnych eksperymentów — idealne dla ciekawskich w każdym wieku.",
  },
  {
    id: "mock-lodz-150",
    place_name: "BaseStack Łódź",
    category: "experience",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7618,
    longitude: 19.4558,
    rating: 4.5,
    photo_url: pic("bouldering-climbing-wall"),
    vibe_tags: ["wspinaczka", "bouldering", "sport"],
    description: "Centrum wspinaczki i boulderingu — idealne dla miłośników aktywnego spędzania czasu.",
  },
  {
    id: "mock-lodz-151",
    place_name: "Arena Laser Games",
    category: "experience",
    city: "Łódź",
    address: "Łódź",
    latitude: 51.7605,
    longitude: 19.4545,
    rating: 4.4,
    photo_url: pic("laser-tag-arena-game"),
    vibe_tags: ["laser tag", "gry", "aktywnie"],
    description: "Arena do gry w laser tag — strzelanka na żywo w labiryntach ze światłem i dźwiękiem.",
  },
  {
    id: "mock-lodz-152",
    place_name: "Tkalnia Zagadek",
    category: "experience",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7580,
    longitude: 19.4590,
    rating: 4.6,
    photo_url: pic("escape-room-textile-theme"),
    vibe_tags: ["escape room", "zagadki", "klimat"],
    description: "Łódzkie escape roomy w tematyce włókienniczej — zagadki i pułapki w klimatycznym wnętrzu.",
  },
  {
    id: "mock-lodz-153",
    place_name: "Let Me Out - escape room",
    category: "experience",
    city: "Łódź",
    address: "ul. Piotrkowska, 90-001 Łódź",
    latitude: 51.7610,
    longitude: 19.4556,
    rating: 4.5,
    photo_url: pic("escape-room-adventure"),
    vibe_tags: ["escape room", "zagadki", "przygoda"],
    description: "Escape roomy dla grup — różnorodne scenariusze od horroru po przygodę, z wysoką oceną trudności.",
  },
  {
    id: "mock-lodz-154",
    place_name: "Super Strikers",
    category: "experience",
    city: "Łódź",
    address: "Łódź",
    latitude: 51.7622,
    longitude: 19.4560,
    rating: 4.4,
    photo_url: pic("football-simulator-striker"),
    vibe_tags: ["piłka nożna", "symulator", "aktywnie"],
    description: "Centrum z symulatorem piłkarskim — trenuj strzały i technikę jak profesjonalista.",
  },

  // ── Kawiarnia Testowa (business profile demo) ────────────────────────────────
  {
    id: "mock-krakow-biznes-1",
    place_name: "Kawiarnia Testowa",
    category: "cafe",
    city: "Kraków",
    address: "Rynek Główny 1, 31-042 Kraków",
    latitude: 50.0617,
    longitude: 19.9373,
    rating: 4.7,
    photo_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    vibe_tags: ["kawa", "klimat", "slow"],
    description: "Najlepsza kawiarnia w Krakowie. Świetne espresso i domowe ciasta.",
    businessLogoUrl: "", // pusty string = pokaż orb placeholder
    businessEventTitle: "Happy hour 16:00–18:00, drinki 1+1",
    galleryPhotos: [
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
      "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80",
    ],
  },
];

export const MOCK_BUSINESS_POSTS = [
  {
    id: "mock-post-1",
    description: "Właśnie wjechała nowa karta sezonowa ☕ Latte z lawendą i macha cold brew — dostępne od dziś!",
    photo_urls: ["https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80"],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(), // 3h temu
  },
  {
    id: "mock-post-2",
    description: "Happy hour dziś od 16:00 do 18:00 — wszystkie drinki w cenie 1+1. Zapraszamy! 🎉",
    photo_urls: [],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 dni temu
  },
];

export function getMockPlaces(city: string): MockPlace[] {
  const cityLower = city.toLowerCase();
  return MOCK_PLACES.filter(p => p.city.toLowerCase() === cityLower);
}

export const MOCK_PLACE_DETAIL = {
  formatted_address: "ul. Przykładowa 1, Kraków",
  formatted_phone_number: "+48 12 345 67 89",
  opening_hours: {
    weekday_text: [
      "poniedziałek: 9:00–20:00",
      "wtorek: 9:00–20:00",
      "środa: 9:00–20:00",
      "czwartek: 9:00–20:00",
      "piątek: 9:00–21:00",
      "sobota: 10:00–21:00",
      "niedziela: 10:00–18:00",
    ],
    open_now: true,
  },
  rating: 4.5,
  user_ratings_total: 1234,
  website: "https://example.com",
  photos: [],
  reviews: [
    {
      author_name: "Anna K.",
      rating: 5,
      text: "Świetne miejsce, bardzo polecam! Byłam tu kilka razy i zawsze super.",
      relative_time_description: "tydzień temu",
    },
    {
      author_name: "Marek W.",
      rating: 4,
      text: "Dobre miejsce na popołudniowy spacer. Miło spędzony czas.",
      relative_time_description: "2 tygodnie temu",
    },
  ],
};
