-- Uzupelnienie miejsc Trojmiasto (Gdansk + Gdynia) 2026-08-05
-- Luzny import: nazwa + miasto + kategoria + address(=miasto do wyszukania na mapie).
-- BEZ zdjec (photo_url NULL -> ikona kategorii na tle #fcede3) i BEZ opisow AI.
-- Dedup vs istniejace 867 miejsc zrobiony przy generowaniu (46 naprawde nowych).
-- Link 'Zobacz w Google Maps' budowany z place_name + address, wiec coords niepotrzebne.

INSERT INTO public.places (city, place_name, category, address, is_active) VALUES
('Gdańsk', 'Pomnik Obrońców Wybrzeża - Westerplatte', 'monument', 'Gdańsk', true),
('Gdańsk', 'Archikatedra Oliwska', 'monument', 'Gdańsk', true),
('Gdańsk', 'Pomnik Poległych Stoczniowców 1970', 'monument', 'Gdańsk', true),
('Gdańsk', 'Bazylika św. Mikołaja', 'monument', 'Gdańsk', true),
('Gdańsk', 'Bazylika św. Brygidy', 'monument', 'Gdańsk', true),
('Gdańsk', 'Wielka Zbrojownia', 'monument', 'Gdańsk', true),
('Gdańsk', 'Kościół św. Katarzyny', 'monument', 'Gdańsk', true),
('Gdańsk', 'Murale w dzielnicy Zaspa', 'monument', 'Gdańsk', true),
('Gdańsk', 'Złota Kamienica', 'monument', 'Gdańsk', true),
('Gdańsk', 'Molo w Brzeźnie', 'monument', 'Gdańsk', true),
('Gdańsk', 'Stary Żuraw Portowy nad Motławą', 'monument', 'Gdańsk', true),
('Gdańsk', 'Fontanna Neptuna', 'monument', 'Gdańsk', true),
('Gdańsk', 'Złota Brama', 'monument', 'Gdańsk', true),
('Gdańsk', 'Zielona Brama', 'monument', 'Gdańsk', true),
('Gdańsk', 'Brama Wyżynna', 'monument', 'Gdańsk', true),
('Gdańsk', 'Stocznia Cesarska - Imperial Shipyard', 'monument', 'Gdańsk', true),
('Gdańsk', 'Dwór Artusa', 'museum', 'Gdańsk', true),
('Gdańsk', 'Stołówka Gdańska', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'Ambrello', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'Plaża Przymorze', 'park', 'Gdańsk', true),
('Gdańsk', 'Plaża Sobieszewska', 'park', 'Gdańsk', true),
('Gdańsk', 'ŁĄKA BAR', 'bar', 'Gdańsk', true),
('Gdańsk', 'Pub Red Light', 'bar', 'Gdańsk', true),
('Gdańsk', 'poparzeni', 'cafe', 'Gdańsk', true),
('Gdańsk', 'pokusa', 'cafe', 'Gdańsk', true),
('Gdańsk', 'vana', 'cafe', 'Gdańsk', true),
('Gdańsk', 'must bake', 'cafe', 'Gdańsk', true),
('Gdańsk', 'Gyozilla Ramen Chmielna', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'Węzeł Cieplny', 'bar', 'Gdańsk', true),
('Gdańsk', 'Tostoxo', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'Palec do budki 2.0 Garnizon', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'Oni Ramen', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'Flux', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'SLOW', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'BRUT Bistro', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'cacko', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'husak', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'Cały Gaweł', 'restaurant', 'Gdańsk', true),
('Gdańsk', 'Kompozyt Cafe', 'cafe', 'Gdańsk', true),
('Gdańsk', 'Kawiarnia Las Oliwa', 'cafe', 'Gdańsk', true),
('Gdańsk', 'Kawiarnia Ratuszowa', 'cafe', 'Gdańsk', true),
('Gdańsk', 'Kolonia artystów', 'cafe', 'Gdańsk', true),
('Gdańsk', 'Lumpik', 'shopping', 'Gdańsk', true),
('Gdańsk', 'Palmiarnia', 'experience', 'Gdańsk', true),
('Gdańsk', 'Magnolia Studio', 'experience', 'Gdańsk', true),
('Gdynia', 'Akwarium Gdyńskie MIR', 'experience', 'Gdynia', true);
