-- ─── Gdańsk places ────────────────────────────────────────────────────────────
-- Coordinates: NULL — proxy falls back to text-search when coords are absent.
-- Categories map to GroupSession AVAILABLE_CATEGORIES dbValues.

INSERT INTO public.places (city, place_name, category, is_active, vibe_tags) VALUES

-- ── Kawiarnia (cafe) ──────────────────────────────────────────────────────────
('Gdańsk', 'Balans Coffee Speciality & Breakfast', 'cafe', true, ARRAY['specialty coffee', 'śniadania']),
('Gdańsk', 'Kawiarnia Drukarnia', 'cafe', true, ARRAY['klimatyczna', 'vintage']),
('Gdańsk', 'Kawiarnia Retro', 'cafe', true, ARRAY['retro', 'klimatyczna']),
('Gdańsk', 'Perro Negro Kaffe', 'cafe', true, ARRAY['specialty coffee', 'minimalizm']),
('Gdańsk', 'UMAM Cukiernia Gdańska', 'cafe', true, ARRAY['ciasta', 'cukiernia']),
('Gdańsk', 'Józef K.', 'cafe', true, ARRAY['klimatyczna', 'literacka']),
('Gdańsk', 'Plenum', 'cafe', true, ARRAY['specialty coffee', 'design']),
('Gdańsk', 'Marina Cafe', 'cafe', true, ARRAY['widok na wodę', 'marina']),
('Gdańsk', 'Cafe Kamienica', 'cafe', true, ARRAY['klimatyczna', 'zabytkowa']),
('Gdańsk', 'Fika', 'cafe', true, ARRAY['skandynawska', 'ciasta']),
('Gdańsk', 'Pikawa', 'cafe', true, ARRAY['specialty coffee', 'lokalna']),
('Gdańsk', 'W Starym Kadrze', 'cafe', true, ARRAY['klimatyczna', 'artystyczna']),
('Gdańsk', 'Doppio Club Cafe', 'cafe', true, ARRAY['specialty coffee', 'club']),
('Gdańsk', 'MOYA MATCHA GDAŃSK', 'cafe', true, ARRAY['matcha', 'zdrowe']),
('Gdańsk', 'Leń', 'cafe', true, ARRAY['relaks', 'slow']),
('Gdańsk', 'Kotka Cafe', 'cafe', true, ARRAY['kocia kawiarnia', '14+']),
('Gdańsk', 'z Innej Parafii', 'cafe', true, ARRAY['klimatyczna', 'alternatywna']),
('Gdańsk', 'Matko i Córko Cafe', 'cafe', true, ARRAY['rodzinna', 'ciasta']),
('Gdańsk', 'Sips.Gdansk', 'cafe', true, ARRAY['specialty coffee', 'nowoczesna']),
('Gdańsk', 'Słodko Słono', 'cafe', true, ARRAY['słodycze', 'kanapki']),
('Gdańsk', 'Fukafe', 'cafe', true, ARRAY['klimatyczna', 'hipsterska']),
('Gdańsk', 'Nurt Cafe & Sandwiches', 'cafe', true, ARRAY['kanapki', 'specialty coffee']),
('Gdańsk', 'Cafe Luis Gdańsk', 'cafe', true, ARRAY['klimatyczna', 'centrum']),
('Gdańsk', 'GingerKawa', 'cafe', true, ARRAY['imbirowa', 'specialty coffee']),
('Gdańsk', 'Cukropelka', 'cafe', true, ARRAY['ciasta', 'słodycze']),
('Gdańsk', 'Gdańska Palarnia Kawy - Rodziny Banaczków', 'cafe', true, ARRAY['palarnia', 'specialty coffee']),
('Gdańsk', 'Lang.fuhr', 'cafe', true, ARRAY['klimatyczna', 'historyczna']),
('Gdańsk', 'Kawiarnia CzKawka', 'cafe', true, ARRAY['lokalna', 'klimatyczna']),
('Gdańsk', 'Sztuka Wyboru', 'cafe', true, ARRAY['specialty coffee', 'artystyczna']),
('Gdańsk', 'ZORZA Kawiarnia / Kwiaciarnia', 'cafe', true, ARRAY['kwiaty', 'klimatyczna']),
('Gdańsk', 'Spokój Café', 'cafe', true, ARRAY['relaks', 'spokój']),
('Gdańsk', 'Kawiarnia PUBLICZNA', 'cafe', true, ARRAY['klimatyczna', 'centrum']),

-- ── Piekarnia → cafe ─────────────────────────────────────────────────────────
('Gdańsk', 'Chimney - kołacze węgierskie i lody', 'cafe', true, ARRAY['kołacze', 'lody', 'węgierska']),
('Gdańsk', 'PIEKARNIA GRUZIŃSKA KETiLi PURi', 'cafe', true, ARRAY['gruzińska', 'pieczywo', 'egzotyczna']),
('Gdańsk', 'Tomasz Deker', 'cafe', true, ARRAY['cukiernia', 'desery']),
('Gdańsk', 'Piekarnia Gdańsk', 'cafe', true, ARRAY['piekarnia', 'śniadania']),

-- ── Cukiernia → cafe ─────────────────────────────────────────────────────────
('Gdańsk', 'Paulo Gelateria', 'cafe', true, ARRAY['lody', 'gelateria', 'włoska']),
('Gdańsk', 'Lody Soprano', 'cafe', true, ARRAY['lody', 'włoska']),
('Gdańsk', 'Dickery', 'cafe', true, ARRAY['ciasta', 'desery']),
('Gdańsk', 'Eklerownia', 'cafe', true, ARRAY['eklery', 'cukiernia']),
('Gdańsk', 'Le Delice bistro-piekarnia-cukiernia-lodziarnia', 'cafe', true, ARRAY['cukiernia', 'piekarnia', 'lody']),

-- ── Restauracja ───────────────────────────────────────────────────────────────
('Gdańsk', 'Pan Papuga - Restauracja Gdańsk', 'restaurant', true, ARRAY['polska', 'klimatyczna']),
('Gdańsk', 'Treinta y Tres', 'restaurant', true, ARRAY['latynoska', 'wino']),
('Gdańsk', 'Literacka Restaurant & Wine Bar', 'restaurant', true, ARRAY['wino', 'fine dining']),
('Gdańsk', 'Restauracja TYGLE', 'restaurant', true, ARRAY['polska', 'nowoczesna']),
('Gdańsk', 'Whiskey in the Jar', 'restaurant', true, ARRAY['irish', 'whisky', 'pub']),
('Gdańsk', 'Restauracja TRUE', 'restaurant', true, ARRAY['nowoczesna', 'polska']),
('Gdańsk', 'Pierogarnia Stary Młyn Gdańsk Św. Ducha', 'restaurant', true, ARRAY['pierogi', 'polska']),
('Gdańsk', 'Pomelo Gdańsk', 'restaurant', true, ARRAY['azjatycka', 'fusion']),
('Gdańsk', 'ORIA MAGIC HOUSE restauracja', 'restaurant', true, ARRAY['magiczna', 'klimatyczna']),
('Gdańsk', 'Manna 68', 'restaurant', true, ARRAY['wegetariańska', 'zdrowa']),
('Gdańsk', 'Restauracja Mezalians Gdańsk', 'restaurant', true, ARRAY['fine dining', 'polska']),
('Gdańsk', 'Hewelke Restauracja i Piekarnia', 'restaurant', true, ARRAY['polska', 'piekarnia']),
('Gdańsk', 'Ostro', 'restaurant', true, ARRAY['owoce morza', 'ryby']),
('Gdańsk', 'Billy''s American Restaurants Wyspa Spichrzów', 'restaurant', true, ARRAY['american', 'casual']),
('Gdańsk', 'Targ Rybny - Fishmarkt', 'restaurant', true, ARRAY['ryby', 'owoce morza', 'historyczna']),
('Gdańsk', 'Piwna47 Food & Wine Bar', 'restaurant', true, ARRAY['wino', 'tapas']),
('Gdańsk', 'Restauracja Goldwasser', 'restaurant', true, ARRAY['historyczna', 'polska', 'premium']),
('Gdańsk', 'ELIKSIR Restaurant & Cocktailbar', 'restaurant', true, ARRAY['koktajle', 'nowoczesna']),
('Gdańsk', 'Restauracja Pueblo', 'restaurant', true, ARRAY['meksykańska', 'latynoska']),
('Gdańsk', 'Calma Pasta Fresca', 'restaurant', true, ARRAY['włoska', 'pasta', 'świeża']),
('Gdańsk', 'Stołówka Gdańska', 'restaurant', true, ARRAY['polska', 'domowa', 'casual']),
('Gdańsk', 'Pizzarium 01', 'restaurant', true, ARRAY['pizza', 'włoska']),
('Gdańsk', 'MONTOWNIA FOOD HALL', 'restaurant', true, ARRAY['food hall', 'różnorodna']),
('Gdańsk', 'La Pampa Steakhouse', 'restaurant', true, ARRAY['steki', 'mięso', 'argentyńska']),
('Gdańsk', 'Restauracja Ritz', 'restaurant', true, ARRAY['elegancka', 'polska']),
('Gdańsk', 'Restauracja Motlava', 'restaurant', true, ARRAY['widok na wodę', 'polska']),
('Gdańsk', 'Durga', 'restaurant', true, ARRAY['indyjska', 'egzotyczna']),
('Gdańsk', 'Thai Thai Gdańsk', 'restaurant', true, ARRAY['tajska', 'azjatycka']),
('Gdańsk', 'ArtBistro by Progres. Restauracja Gdańsk Wrzeszcz', 'restaurant', true, ARRAY['artystyczna', 'bistro']),
('Gdańsk', 'Hola Tapas', 'restaurant', true, ARRAY['tapas', 'hiszpańska']),
('Gdańsk', 'Chleb i Wino Stągiewna Gdańsk', 'restaurant', true, ARRAY['wino', 'polska', 'klimatyczna']),
('Gdańsk', 'Viceversa', 'restaurant', true, ARRAY['włoska', 'nowoczesna']),
('Gdańsk', 'Pierogarnia Mandu Gdańsk Śródmieście', 'restaurant', true, ARRAY['pierogi', 'polska']),
('Gdańsk', 'Babette – pracownia zupy i chleba', 'restaurant', true, ARRAY['zupy', 'chleb', 'domowa']),
('Gdańsk', 'Niesztuka Restaurant&Bar', 'restaurant', true, ARRAY['nowoczesna', 'bar']),
('Gdańsk', 'Swojski Smak', 'restaurant', true, ARRAY['polska', 'domowa', 'tradycyjna']),
('Gdańsk', 'Hora de España', 'restaurant', true, ARRAY['hiszpańska', 'tapas']),
('Gdańsk', 'Gdański Bowke', 'restaurant', true, ARRAY['bowle', 'zdrowa', 'nowoczesna']),
('Gdańsk', 'Crazy Butcher Gdańsk Butchery & Bistro', 'restaurant', true, ARRAY['mięso', 'steki', 'bistro']),
('Gdańsk', 'Nie/Mięsny Dolne Miasto', 'restaurant', true, ARRAY['wegetariańska', 'wegańska']),
('Gdańsk', 'Restauracja Canis', 'restaurant', true, ARRAY['fine dining', 'nowoczesna']),
('Gdańsk', 'Słony Spichlerz - Food Hall', 'restaurant', true, ARRAY['food hall', 'różnorodna']),
('Gdańsk', 'Restauracja Geneza Jedzenia i Wina Gdańsk', 'restaurant', true, ARRAY['wino', 'fine dining']),
('Gdańsk', 'Vis a Vis Restauracja & Bar', 'restaurant', true, ARRAY['widok', 'bar']),
('Gdańsk', '100cznia', 'restaurant', true, ARRAY['polska', 'casual']),

-- ── Bar ───────────────────────────────────────────────────────────────────────
('Gdańsk', 'Smoki i Lochy - pub z planszówkami', 'bar', true, ARRAY['planszówki', 'pub', 'gry']),
('Gdańsk', 'SASSY Roof Top Cocktail Bar & Club', 'bar', true, ARRAY['rooftop', 'koktajle', 'widok']),
('Gdańsk', 'Fibonacci Aperitivo Bar', 'bar', true, ARRAY['aperitivo', 'koktajle', 'włoski styl']),
('Gdańsk', 'Grass British Sports Bar', 'bar', true, ARRAY['sports bar', 'british', 'piłka nożna']),
('Gdańsk', 'Bar Leon', 'bar', true, ARRAY['koktajle', 'klimatyczny']),
('Gdańsk', 'El Mariachi Tequila & Cocktail Bar', 'bar', true, ARRAY['tequila', 'meksykański', 'koktajle']),
('Gdańsk', 'Irish Pub Piwnica', 'bar', true, ARRAY['irish pub', 'piwo', 'klimatyczny']),
('Gdańsk', 'No To Cyk', 'bar', true, ARRAY['piwo', 'lokalne', 'casual']),
('Gdańsk', 'UWAGA PIWO Piwna', 'bar', true, ARRAY['craft beer', 'piwo rzemieślnicze']),

-- ── Muzeum ────────────────────────────────────────────────────────────────────
('Gdańsk', 'Muzeum II Wojny Światowej w Gdańsku', 'museum', true, ARRAY['historia', 'II WŚ', 'nowoczesne']),
('Gdańsk', 'Europejskie Centrum Solidarności', 'museum', true, ARRAY['historia', 'solidarność', 'nowoczesne']),
('Gdańsk', 'Zespół Przedbramia - Muzeum Gdańska', 'museum', true, ARRAY['historia', 'średniowiecze', 'architektura']),
('Gdańsk', 'Muzeum Gdańska - Ratusz Głównego Miasta', 'museum', true, ARRAY['historia', 'architektura', 'centrum']),
('Gdańsk', 'Muzeum Bursztynu. Oddział Muzeum Gdańska', 'museum', true, ARRAY['bursztyn', 'unikat', 'Gdańsk']),
('Gdańsk', 'Gdański Bazar Natury', 'museum', true, ARRAY['natura', 'edukacja']),
('Gdańsk', 'Muzeum Narodowe w Gdańsku', 'museum', true, ARRAY['sztuka', 'historia', 'kolekcje']),
('Gdańsk', 'Narodowe Muzeum Morskie w Gdańsku', 'museum', true, ARRAY['morze', 'statki', 'historia']),
('Gdańsk', 'Hevelianum', 'museum', true, ARRAY['nauka', 'historia', 'interaktywne']),
('Gdańsk', 'Twierdza Wisłoujście. Oddział Muzeum Gdańska', 'museum', true, ARRAY['twierdza', 'historia', 'architektura']),
('Gdańsk', 'DeJa Vu Muzeum', 'museum', true, ARRAY['interaktywne', 'iluzje']),
('Gdańsk', 'Muzeum Gier Wideo - Gdańsk Arcade Museum', 'museum', true, ARRAY['gry', 'retro', 'nostalgiczne']),
('Gdańsk', 'Galeria Starych Zabawek', 'museum', true, ARRAY['zabawki', 'retro', 'nostalgiczne']),
('Gdańsk', 'Ośrodek Kultury Morskiej. Oddział Narodowego Muzeum Morskiego', 'museum', true, ARRAY['morze', 'kultura', 'historia']),
('Gdańsk', 'Muzeum Nauki Gdańskiej. Oddział Muzeum Gdańska', 'museum', true, ARRAY['nauka', 'edukacja']),

-- ── Punkt widokowy → monument ─────────────────────────────────────────────────
('Gdańsk', 'Olivia Star', 'monument', true, ARRAY['widok', 'nowoczesne', 'panorama']),
('Gdańsk', 'Góra Gradowa', 'monument', true, ARRAY['widok', 'wzgórze', 'historyczna']),
('Gdańsk', 'Wieża widokowa na wzgórzu Pachołek', 'monument', true, ARRAY['widok', 'natura', 'wieża']),

-- ── Park ──────────────────────────────────────────────────────────────────────
('Gdańsk', 'Park Hevelianum', 'park', true, ARRAY['park', 'spacer', 'wzgórze']),
('Gdańsk', 'Park Oliwski im. Adama Mickiewicza', 'park', true, ARRAY['ogród botaniczny', 'spacer', 'katedra']),
('Gdańsk', 'Park Prezydenta Ronalda Reagana', 'park', true, ARRAY['park', 'spacer', 'rodzinny']),
('Gdańsk', 'Park Oruński im. Emilii Hoene', 'park', true, ARRAY['park', 'spacer', 'natura']),

-- ── Zakupy → market ───────────────────────────────────────────────────────────
('Gdańsk', 'Forum Gdańsk', 'market', true, ARRAY['galeria', 'zakupy', 'centrum']),
('Gdańsk', 'Designer Outlet Gdańsk', 'market', true, ARRAY['outlet', 'marki', 'okazje']),
('Gdańsk', 'Pchli Targ w Oliwie', 'market', true, ARRAY['pchli targ', 'vintage', 'antyki']),

-- ── Rozrywka → experience ─────────────────────────────────────────────────────
('Gdańsk', 'Ulica Elektryków', 'experience', true, ARRAY['street food', 'muzyka', 'spotkania']),
('Gdańsk', 'Pixel XL', 'experience', true, ARRAY['gry', 'konsole', 'rozrywka']),
('Gdańsk', 'Baszta Tajemnic - Centrum Rozrywki', 'experience', true, ARRAY['escape room', 'przygoda', 'rozrywka']),
('Gdańsk', 'JUMPCITY Gdańsk', 'experience', true, ARRAY['trampoliny', 'aktywny', 'sport']),
('Gdańsk', 'Loopy''s World - Rodzinne Centrum Rozrywki w Gdańsku', 'experience', true, ARRAY['rodzinna', 'aktywna', 'dzieci']),
('Gdańsk', 'Movement Arena Gdańsk - PARKOUR | TRAMPOLINY | NINJA', 'experience', true, ARRAY['parkour', 'trampoliny', 'sport', 'aktywny']);
