-- Real Łódź places imported from user's CSV
-- Categories mapping: Kawiarnia/Piekarnia/Śniadania → cafe, Restauracja → restaurant,
-- Bar → bar, Muzeum → museum, Park → park, Market → market,
-- Landmark → monument, Rozrywka → experience

INSERT INTO public.places (city, place_name, category) VALUES

-- ── KAWIARNIE ────────────────────────────────────────────────
('Łódź', 'The Brick Coffee Factory', 'cafe'),
('Łódź', 'The Brick Coffee Factory', 'cafe'),
('Łódź', 'Przędza', 'cafe'),
('Łódź', 'Tubajka', 'cafe'),
('Łódź', 'Pijalnia Czekolady E.Wedel', 'cafe'),
('Łódź', 'Pijalnia Czekolady E.Wedel', 'cafe'),
('Łódź', 'Fit Cake Łódź Księży Młyn', 'cafe'),
('Łódź', 'The White Bear Coffee Łódź ul. Traugutta', 'cafe'),
('Łódź', 'Szykier Coffee & Bistro', 'cafe'),
('Łódź', 'Grand Café', 'cafe'),
('Łódź', 'Klubokawiarnia Owoce i Warzywa', 'cafe'),
('Łódź', 'Klubokawiarnia Owoce i Warzywa', 'cafe'),
('Łódź', 'Chatka Ech', 'cafe'),
('Łódź', 'Costa Coffee', 'cafe'),
('Łódź', 'Starbucks', 'cafe'),
('Łódź', 'Coffeehood', 'cafe'),
('Łódź', 'Podkawa Palarnia Kawy', 'cafe'),
('Łódź', 'Kraftowa', 'cafe'),
('Łódź', 'Coffee to Go', 'cafe'),
('Łódź', 'Ola! de Nata', 'cafe'),
('Łódź', 'Kubek Coffee Matcha Specialty Coffee Gofry', 'cafe'),
('Łódź', 'Café Book&Cook', 'cafe'),
('Łódź', 'Kawiarnia Magazyn Kawy', 'cafe'),
('Łódź', 'Hot Air Cafe', 'cafe'),
('Łódź', 'Pan tu nie stał - cafe bar', 'cafe'),
('Łódź', 'PAJ', 'cafe'),
('Łódź', 'KIOSK', 'cafe'),
('Łódź', 'Koleżanki Cafe', 'cafe'),
('Łódź', 'FAVE Izabela Stręk', 'cafe'),
('Łódź', 'HYT - pracownia baristyczna', 'cafe'),
('Łódź', 'Qubek Cafe', 'cafe'),
('Łódź', 'Vita Cafe', 'cafe'),
('Łódź', 'Kawiarnia Ekspres do kawy KROKUSOWA', 'cafe'),
('Łódź', 'Cafe Verte', 'cafe'),
('Łódź', 'Prosto z Mostu klubokawiarnia', 'cafe'),
('Łódź', 'KAWIARNIA EKSPRES DO KAWY', 'cafe'),
('Łódź', 'Karmello Chocolatier', 'cafe'),
('Łódź', 'Mono Cafe & Bistro', 'cafe'),
('Łódź', 'Empatia Sweet', 'cafe'),

-- ── PIEKARNIE ────────────────────────────────────────────────
('Łódź', 'Montag', 'cafe'),
('Łódź', 'Receptura cukiernia piekarnia', 'cafe'),
('Łódź', 'OKRUCHY mikropiekarnia', 'cafe'),
('Łódź', 'La Polacco - Piekarnia & Cukiernia', 'cafe'),
('Łódź', 'Gorący Precel F-Wiatrak', 'cafe'),
('Łódź', 'Piekarz Cake & Coffee', 'cafe'),
('Łódź', 'Pan Precel', 'cafe'),

-- ── ŚNIADANIA ────────────────────────────────────────────────
('Łódź', 'Caffe przy ulicy Śródmieście', 'cafe'),
('Łódź', 'Caffe przy ulicy Bałuty', 'cafe'),
('Łódź', 'Caffe przy ulicy Retkinia', 'cafe'),
('Łódź', 'Chałka i Masło', 'cafe'),
('Łódź', 'Breadnia', 'cafe'),
('Łódź', 'Bułkę przez Bibułkę Łódź', 'cafe'),
('Łódź', 'MORNING coffee & more Dąbrowa', 'cafe'),
('Łódź', 'MORNING coffee & more Polesie', 'cafe'),

-- ── RESTAURACJE ──────────────────────────────────────────────
('Łódź', 'FaBuła Bistro', 'restaurant'),
('Łódź', 'Manekin', 'restaurant'),
('Łódź', 'Pierogarnia Stary Młyn Łódź', 'restaurant'),
('Łódź', 'Whiskey in the Jar', 'restaurant'),
('Łódź', 'Ristorante Mare e Monti', 'restaurant'),
('Łódź', 'ANATEWKA', 'restaurant'),
('Łódź', 'Ato Ramen', 'restaurant'),
('Łódź', 'Galicja', 'restaurant'),
('Łódź', 'Aloha by Las Palmas', 'restaurant'),
('Łódź', 'Imber', 'restaurant'),
('Łódź', 'Otwarte Drzwi', 'restaurant'),
('Łódź', 'Al Dente Pasta & Bąble Bar', 'restaurant'),
('Łódź', 'Złoty Imbir', 'restaurant'),
('Łódź', 'Wolność Neo Bistro', 'restaurant'),
('Łódź', 'Ato Sushi', 'restaurant'),
('Łódź', 'Bawełna - Restauracja Manufaktura', 'restaurant'),
('Łódź', 'Lavash - Restauracja Gruzińska i Ormiańska', 'restaurant'),
('Łódź', 'Señoritas Restaurant & Lounge', 'restaurant'),
('Łódź', 'Susharnia', 'restaurant'),
('Łódź', 'Tango Argentino Steakhouse', 'restaurant'),
('Łódź', 'Restauracja Roma', 'restaurant'),
('Łódź', 'Tawerna Pepe Verde', 'restaurant'),
('Łódź', 'Trattoria Italiana', 'restaurant'),
('Łódź', 'Winni', 'restaurant'),
('Łódź', 'Len i Bawełna - Restauracja Off Piotrkowska', 'restaurant'),
('Łódź', 'Ukryte Rzeki', 'restaurant'),
('Łódź', 'Hot Spoon', 'restaurant'),
('Łódź', 'Pizzeria Osiedlowa Pizza Łódź Chojny', 'restaurant'),
('Łódź', 'Pizzeria Osiedlowa Pizza Burger Łódź Centrum', 'restaurant'),
('Łódź', 'Restauracja Laxmi Indyjska', 'restaurant'),
('Łódź', 'Restauracja Piwnica Łódzka', 'restaurant'),
('Łódź', 'King Kong Thai Food', 'restaurant'),
('Łódź', 'Polka', 'restaurant'),
('Łódź', 'Pierogarnia TEREMOK przy Piramowicza', 'restaurant'),
('Łódź', 'A tu...TAJ', 'restaurant'),
('Łódź', 'Perlyna Ukrainy', 'restaurant'),
('Łódź', 'Spółdzielnia', 'restaurant'),
('Łódź', 'Restauracja Alpejska Łódź Górna', 'restaurant'),
('Łódź', 'Tłusty Śledź Smażalnia ryb', 'restaurant'),
('Łódź', 'Restauracja Delight', 'restaurant'),
('Łódź', 'Fatamorgana', 'restaurant'),
('Łódź', 'DOKI Gastrobar', 'restaurant'),
('Łódź', 'Restauracja Ogień i Sól', 'restaurant'),
('Łódź', 'Restauracja Manuarte', 'restaurant'),

-- ── BARY ─────────────────────────────────────────────────────
('Łódź', 'Long Play', 'bar'),
('Łódź', 'Football Pub', 'bar'),
('Łódź', 'Pijalnia Wódki i Piwa', 'bar'),
('Łódź', 'Bistro', 'bar'),
('Łódź', 'Pijana Wiśnia', 'bar'),
('Łódź', 'Kij', 'bar'),
('Łódź', 'Czupito', 'bar'),
('Łódź', 'Pub GALANTA 7', 'bar'),
('Łódź', 'Spaleni Słońcem', 'bar'),

-- ── MUZEA ────────────────────────────────────────────────────
('Łódź', 'Muzeum Pałac Herbsta Oddział Muzeum Sztuki w Łodzi', 'museum'),
('Łódź', 'Muzeum Kinematografii w Łodzi', 'museum'),
('Łódź', 'Muzeum Światła Łódź', 'museum'),
('Łódź', 'Planetarium EC1', 'museum'),
('Łódź', 'Centralne Muzeum Włókiennictwa w Łodzi', 'museum'),
('Łódź', 'Stacja Radegast Muzeum Tradycji Niepodległościowych w Łodzi', 'museum'),
('Łódź', 'Muzeum Miasta Łodzi', 'museum'),
('Łódź', 'Centrum Nauki i Techniki EC1', 'museum'),
('Łódź', 'Muzeum Sztuki w Łodzi MS1', 'museum'),
('Łódź', 'Muzeum Fabryki', 'museum'),
('Łódź', 'Muzeum Tradycji Niepodległościowych Oddział Martyrologii Radogoszcz', 'museum'),
('Łódź', 'Zajezdnia Muzealna BRUS w Łodzi', 'museum'),
('Łódź', 'Centrum Komiksu i Narracji Interaktywnej EC1', 'museum'),
('Łódź', 'Muzeum Sztuki w Łodzi MS2', 'museum'),

-- ── PARKI ────────────────────────────────────────────────────
('Łódź', 'Orientarium ZOO Łódź', 'park'),
('Łódź', 'Ogród Botaniczny w Łodzi', 'park'),
('Łódź', 'Park Ocalałych', 'park'),
('Łódź', 'Stawy Jana', 'park'),
('Łódź', 'Park im. 1 Maja w Łodzi', 'park'),
('Łódź', 'Park Źródliska', 'park'),
('Łódź', 'Park na Młynku', 'park'),

-- ── MARKETY ──────────────────────────────────────────────────
('Łódź', 'Manufaktura', 'market'),
('Łódź', 'OFF Piotrkowska', 'market'),
('Łódź', 'Nowa Sukcesja', 'market'),
('Łódź', 'Book Się Rodzi', 'market'),
('Łódź', 'Silva Rerum', 'market'),
('Łódź', 'Piotrkowska59', 'market'),
('Łódź', 'Noteka', 'market'),
('Łódź', 'Folkstar Łódź', 'market'),

-- ── ZABYTKI / ATRAKCJE ───────────────────────────────────────
('Łódź', 'Pasaż Róży', 'monument'),
('Łódź', 'Cmentarz Żydowski w Łodzi', 'monument'),
('Łódź', 'Księży Młyn', 'monument'),
('Łódź', 'Pałac Karola Poznańskiego', 'monument'),
('Łódź', 'Kamienica Pod Gutenbergiem', 'monument'),
('Łódź', 'Bazylika Archikatedralna pw. św. Stanisława Kostki', 'monument'),
('Łódź', 'Fortepian Rubinsteina', 'monument'),
('Łódź', 'Monopolis', 'monument'),
('Łódź', 'Litzmannstadt Ghetto', 'monument'),
('Łódź', 'Dupa Tuwima', 'monument'),
('Łódź', 'Kaplica Karola Scheiblera', 'monument'),
('Łódź', 'Mural Narodziny Dnia', 'monument'),

-- ── ROZRYWKA ─────────────────────────────────────────────────
('Łódź', 'SALTOS park trampolin', 'experience'),
('Łódź', 'Virtual House', 'experience'),
('Łódź', 'RaceSpot symulatory cocktail bar', 'experience'),
('Łódź', 'Centrum Nauki Experymentarium', 'experience'),
('Łódź', 'BaseStack Łódź', 'experience'),
('Łódź', 'Arena Laser Games', 'experience'),
('Łódź', 'Tkalnia Zagadek', 'experience'),
('Łódź', 'Let Me Out escape room Łódź', 'experience'),
('Łódź', 'Super Strikers', 'experience');
