-- Places: Valletta, Malta
INSERT INTO public.places (city, place_name, category, is_active) VALUES

-- Kawiarnie
('valletta', 'Lot Sixty One Coffee Roasters', 'cafe', true),
('valletta', 'Caffe Cordina', 'cafe', true),
('valletta', 'SUNDAY IN SCOTLAND', 'cafe', true),
('valletta', 'Dolci Peccati', 'cafe', true),
('valletta', 'Croce Bonaci Caterers', 'cafe', true),
('valletta', 'Coffee Circus Lisboa', 'cafe', true),
('valletta', 'Kir Royal Café', 'cafe', true),
('valletta', 'L''Accademia Café', 'cafe', true),
('valletta', 'Frascati Cafè', 'cafe', true),
('valletta', 'Costa Coffee Valletta', 'cafe', true),
('valletta', 'Starbucks Reserve Bar', 'cafe', true),
('valletta', 'Atilem Coffee & Wine', 'cafe', true),
('valletta', 'Mettelina', 'cafe', true),

-- Śniadanie / piekarnie / cukiernie / lodziarnie
('valletta', 'Manouche Craft Bakery & Bistro Valletta', 'cafe', true),
('valletta', 'C. Camilleri Dolceria', 'cafe', true),
('valletta', 'C. Camilleri & Sons Ltd. - Valletta', 'cafe', true),
('valletta', 'the masters Bakery Boutique Valletta', 'cafe', true),
('valletta', 'Sphinx Pastizzeria', 'cafe', true),
('valletta', 'Maiz Bakery', 'cafe', true),
('valletta', 'Vero Gelato', 'cafe', true),
('valletta', 'Tiffany''s gelateria', 'cafe', true),
('valletta', 'Häagen-Dazs', 'cafe', true),
('valletta', 'Evergreen Gelateria', 'cafe', true),
('valletta', 'Yole'' Valletta', 'cafe', true),

-- Restauracje
('valletta', 'Radici Malta', 'restaurant', true),
('valletta', 'I Pupi', 'restaurant', true),
('valletta', 'The Rooftop Restaurant & Lounge Valletta', 'restaurant', true),
('valletta', 'Focacceria Dal Pani', 'restaurant', true),
('valletta', 'Il Ristorantino Italiano', 'restaurant', true),
('valletta', 'Cheeky Monkey Gastropub Valletta', 'restaurant', true),
('valletta', 'AKI - Japanese Restaurant & Cocktail Bar', 'restaurant', true),
('valletta', 'MUŻA Restaurant', 'restaurant', true),
('valletta', 'Grain Street', 'restaurant', true),
('valletta', 'Casa Sotto', 'restaurant', true),
('valletta', 'Piadina Caffe', 'restaurant', true),
('valletta', 'Sally Port Pizzeria', 'restaurant', true),
('valletta', 'Gambit Bistro & Bar', 'restaurant', true),
('valletta', 'Mina''s', 'restaurant', true),
('valletta', 'Fifty Nine Republic', 'restaurant', true),
('valletta', 'Sotto Pinsa Romana Valletta', 'restaurant', true),
('valletta', 'Beati Paoli Restaurant', 'restaurant', true),
('valletta', 'Naan Bar', 'restaurant', true),
('valletta', 'ION Harbour By Simon Rogan', 'restaurant', true),
('valletta', 'Rampila Restaurant', 'restaurant', true),
('valletta', 'Risette', 'restaurant', true),
('valletta', 'one80 St.Christopher Str. Valletta', 'restaurant', true),
('valletta', 'Porticello Restaurant', 'restaurant', true),
('valletta', 'Da Pablo Trattoria di Mare', 'restaurant', true),
('valletta', 'Legligin Restaurant', 'restaurant', true),
('valletta', 'Kingsway Valletta', 'restaurant', true),
('valletta', 'U Bistrot', 'restaurant', true),
('valletta', 'Zero Sei Trattoria Romana', 'restaurant', true),
('valletta', 'Hard Rock Cafe Malta', 'restaurant', true),
('valletta', 'Papannis Restaurant', 'restaurant', true),
('valletta', 'The Harbour Club', 'restaurant', true),
('valletta', 'Guzé', 'restaurant', true),
('valletta', 'Cockney''s Valletta Restaurant', 'restaurant', true),
('valletta', 'Palazzo Preca Restaurant', 'restaurant', true),
('valletta', 'Museum Cafe', 'restaurant', true),
('valletta', 'Drunken Dumpling', 'restaurant', true),
('valletta', 'ORTYGIA Food Experience', 'restaurant', true),
('valletta', 'Noni', 'restaurant', true),
('valletta', 'Farina', 'restaurant', true),
('valletta', 'Ta'' Nenu Valletta', 'restaurant', true),
('valletta', 'San Paolo Naufrago', 'restaurant', true),
('valletta', 'Adesso', 'restaurant', true),
('valletta', 'Sciacca Grill', 'restaurant', true),
('valletta', 'TRiBE Valletta', 'restaurant', true),
('valletta', 'Rubino', 'restaurant', true),
('valletta', 'Under Grain', 'restaurant', true),
('valletta', 'La Pira Maltese Kitchen', 'restaurant', true),
('valletta', 'Mamavon', 'restaurant', true),
('valletta', 'Grano', 'restaurant', true),
('valletta', 'Kaiseki', 'restaurant', true),

-- Bary
('valletta', 'Elements Cocktail Lab', 'bar', true),
('valletta', 'Iber&co.', 'bar', true),
('valletta', 'Ellul Wines & Spirits', 'bar', true),
('valletta', 'White Bridge', 'bar', true),
('valletta', 'The Capitol City Bar', 'bar', true),
('valletta', 'Ta''Lonza', 'bar', true),
('valletta', 'La Bottega', 'bar', true),
('valletta', 'Sailors'' Paradise', 'bar', true),
('valletta', 'Rumi', 'bar', true),
('valletta', 'Bombilla Gastrobar', 'bar', true),
('valletta', 'The Oyster Grotto', 'bar', true),
('valletta', 'DOPO', 'bar', true),
('valletta', 'Rocks | Valletta', 'bar', true),
('valletta', 'City Crown', 'bar', true),
('valletta', 'Tottenham Hotspur Malta Spurs', 'bar', true),
('valletta', 'Carmen Bar', 'bar', true),
('valletta', 'Lolita Bar Strait Street Valletta', 'bar', true),

-- Muzea
('valletta', 'Lascaris War Rooms', 'museum', true),
('valletta', 'Casa Rocca Piccola', 'museum', true),
('valletta', 'Narodowe Muzeum Wojny w Valletcie', 'museum', true),
('valletta', 'Pałac Wielkiego Mistrza', 'museum', true),
('valletta', 'Mysterium Fidei Museum St Catherine''s Monastery and Secret Garden', 'museum', true),
('valletta', 'MUŻA - The National Community Art Museum', 'museum', true),
('valletta', 'Malta Time-Gun Museum', 'museum', true),
('valletta', 'Fortifications Interpretation Centre w Valletcie', 'museum', true),
('valletta', 'Zbrojownia Pałacowa w Valletcie', 'museum', true),
('valletta', 'Valletta Contemporary', 'museum', true),
('valletta', 'Blitz Valletta', 'museum', true),
('valletta', 'Muzeum Archeologiczne w Valletcie', 'museum', true),

-- Architektura / zabytki
('valletta', 'St John''s Co-Cathedral', 'monument', true),
('valletta', 'Bazylika Matki Bożej z Góry Karmel w Valletcie', 'monument', true),
('valletta', 'Muzeum Poczty Malty', 'monument', true),
('valletta', 'Malta Prokatedra św. Pawła w Valletcie', 'monument', true),
('valletta', 'Kościół św. Katarzyny Aleksandryjskiej w Valletcie', 'monument', true),
('valletta', 'Parlament Malty', 'monument', true),

-- Parki
('valletta', 'Górne ogrody Barrakka', 'park', true),
('valletta', 'Dolne ogrody Barrakka', 'park', true),
('valletta', 'Ogrody Hastings', 'park', true),

-- Punkty widokowe / landmarki
('valletta', 'Saluting Battery', 'viewpoint', true),
('valletta', 'Valletta Waterfront', 'viewpoint', true),
('valletta', 'Strait St', 'viewpoint', true),
('valletta', 'Fontanna Trytona w Valletcie', 'viewpoint', true),
('valletta', 'Valletta city gate', 'viewpoint', true),
('valletta', 'Underground Valletta', 'viewpoint', true),
('valletta', 'Plac św. Jerzego', 'viewpoint', true),
('valletta', 'Biblioteka Narodowa Malty', 'viewpoint', true),
('valletta', 'Zajazd Kastylijski', 'viewpoint', true),
('valletta', 'Fort St Elmo', 'viewpoint', true),
('valletta', 'Barrakka Lift', 'viewpoint', true),
('valletta', 'Siege Bell War Memorial', 'viewpoint', true),
('valletta', 'Victoria Gate', 'viewpoint', true),

-- Zakupy
('valletta', 'Is-Suq tal-Belt', 'shopping', true),
('valletta', 'Malta Antiques & Collectables', 'shopping', true),
('valletta', 'The Silversmith''s Shop', 'shopping', true),
('valletta', 'Valletta Open Market', 'shopping', true),
('valletta', 'St Elmo''s Fire Jewellery', 'shopping', true),
('valletta', 'Chocolate District', 'shopping', true),
('valletta', 'Çekçik', 'shopping', true),

-- Rozrywka
('valletta', 'The Malta Experience', 'experience', true),
('valletta', 'Valletta Black Friars Experience', 'experience', true),
('valletta', 'Malta 5D', 'experience', true)

ON CONFLICT DO NOTHING;
